### ISSUE TITLE
Merge zbus_names into zbus

### ISSUE THREAD

**Issue by zeenix** [dbus2/zbus#1006]
The zbus_names was created in the hope that it will be shared by other D-Bus crates, and help us cooperate.

However this didn't happen and looks unlikely to happen for a variety of reasons. Instead, it only creates maintenance burden each time changes are needed in this crate. 

I think it's best if this is merged with zbus itself.

**Comment by elmarco** [comment]
I think the idea of having common types in a shared crate is good. However, pulling serde & zvariant goes against the simple goal. At the very least, they should be made optional. But yes, it's a niche use case. 

To help with maintainance, are you using workspace release tools?

**Comment by zeenix** [comment]
> I think the idea of having common types in a shared crate is good

I used to believe so but experience has taught me that unless they're actually shared with other projects, it's not worth the trouble. A good example of smol-rs. Its sub-crates are nicely split but they are actually being used separately by various projects, so the split is well worth it. 

OTOH, there is also the approach tokio takes: everything is one big crate but feature-gate everything so if you want to only use a specific API, you only enable that. 

I'd be happy to go towards the tokio approach.

**Comment by zeenix** [comment]
> To help with maintainance, are you using workspace release tools?

I tried a few times but I found them too complicated and haven't found any tool that handles release notes in the git tag, like we currently do (I like that we have release notes both in the tag and GitHub release).

However, even if releasing was easy, given that zbus_names have no other users other than zbus after 3 years, I don't think this split is worth it. 

We have to also keep in mind that split increases the cold build times and gives users the impression that we've too many deps (something people bring up every now and then).

**Comment by elmarco** [comment]
Given the relation of zbus_names with zv, I think it could make sense to bring it back under zbus. I don't think the point about maintainance holds much for zbus_address though.

Split doesn't necessarily increase build time, sometime it's the other way around. Pros and cons... the subject isn't closed and not worth to debate here without strong official recommandations.

Regarding the number of dependencies, I think experienced developpers are used to have a growing list of deps that is in the order of hundreds. So people use tools to enforce rules regarding license and build checks. It's pretty much the norm.

**Comment by zeenix** [comment]
> Regarding the number of dependencies, I think experienced developpers are used to have a growing list of deps that is in the order of hundreds. So people use tools to enforce rules regarding license and build checks. It's pretty much the norm.

Unfortunately, we can't just assume all our users to be experienced. Most zbus users are not even familiar with D-Bus, judging from all the questions that come up in issues, GH discussions and Matrix channel. I even encountered zbus contributors, who used other D-Bus crates in some of their projects and dependencies was one of the reasons.

Having said all that, if there would be any practical benefits to having the split, then it's worth it. Take my [xdg-home crate](https://crates.io/crates/xdg-home/reverse_dependencies) for example. It was a very generic use case so it made sense to split it and it got at least [2 other users](https://crates.io/crates/xdg-home/reverse_dependencies) that don't use zbus (or even D-Bus).

There may be some niche use cases where someone needs to parse D-Bus addresses w/o the need for the rest of D-Bus but you have not yet been able to list a single one. Until you do, it's a purely theoretical benefit. This is the main thing I'd suggest you focus on here, if you want to convince me on the split.

> Split doesn't necessarily increase build time, sometime it's the other way around.

Many (most?) people don't really measure things. They just see a lot of deps being downloaded and they just assume. I don't want to cater much for this and don't fear adding deps but I do think a split and addition of deps needs to be justified with compelling enough use case(s).

**Comment by TTWNO** [comment]
We use `zbux_names` as part of both atspi-common and odilia-common to use as part of our types. Our common crates should not depend on anything like async-std or tokio since they are meant to be compatible with minimal targets.

**Comment by zeenix** [comment]
> We use `zbus_names` as part of both atspi-common and odilia-common to use as part of our types.

Gotcha, thanks for letting me know. I was actually planning on closing this since I'm planning on using zbus_names in zbus_macros for checking names for validity at compile-time. _macros can't depend on zbus because it'll create a cyclic dep.
