### ISSUE TITLE
Single-field struct return-type serialization is incorrect

### ISSUE THREAD

**Issue by peterdelevoryas** [dbus2/zbus#1015]
```
use zbus::zvariant::Type;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Type)]
struct Test {
    field: u32,
}

struct Daemon;

#[zbus::interface(
    name = "org.test.stuff",
    proxy(
        gen_blocking = false,
        default_path = "/org/test/stuff",
        default_service = "org.test.stuff",
    ),
)]
impl Daemon {
    async fn return_struct(&mut self) -> Test {
        Test { field: 3 }
    }
}



Err(
    Error {
        context: "Unable to return data",
        source: Variant(
            SignatureMismatch(
                U32,
                "`(u)`",
            ),
        ),
    },
)
```
It should be serialized as `(u)`, but seems to be serialized as `u` (I think). I haven't looked into it very far yet, and don't see any outstanding issues advertising this. Adding another field to the return type's struct resolved it for me.

I haven't been able to reduce the repro very far: https://github.com/peterdelevoryas/zbus-issue-1015

I think it's a recent trunk regression, 4.4.0 doesn't seem to have the issue. I noticed it cause I was trying to submit a change separately, so I'm working from `main`.

**Comment by zeenix** [comment]
Thanks so much. I'm certain this is a regression from the work on:  https://github.com/dbus2/zbus/issues/882. I'll take a look soon.
