### ISSUE TITLE
Selecting interface name at runtime

### ISSUE THREAD

**Issue by mahkoh** [dbus2/zbus#1065]
I have two interface that only differ in their name but have the same business logic. Is there any way to handle this in zbus without having to copy paste all of my code? And without having to use the low level interface since the value of zbus is in its code generation.

**Comment by mahkoh** [comment]
I must have misplaced my time machine because your answer does not help me interoperate with existing software that uses both interfaces.

**Comment by zeenix** [comment]
> I must have misplaced my time machine because your answer does not help me interoperate with existing software that uses both interfaces.

No need for sarcastic remarks. I'm sorry I wasn't able to help. If you've any concrete ideas on how your use case can be supported, please let me know. #1011 might be what you're looking for.

**Comment by mahkoh** [comment]
I've written a small wrapper around the low-level zbus interfaces to accomplish this and also solve some other issues I encountered: https://docs.rs/bussy/latest/bussy/
