### ISSUE TITLE
zbus::fdo::ManagedObjects objects can not be cloned

### ISSUE THREAD

**Issue by yurkobb** [dbus2/zbus#1078]
The following program does not compile:

```rust
use zbus::blocking::fdo::ObjectManagerProxy;
use zbus::blocking::Connection;
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    let conn = Connection::system()?;
    let obj_manager = ObjectManagerProxy::new(
        &conn,
        "org.freedesktop.UDisks2",
        "/org/freedesktop/UDisks2",
    )?;
    let all_objects = obj_manager.get_managed_objects()?;
    let cloned = all_objects.clone();
    Ok(())
}
```

Yielding instead:
```
error[E0599]: the method `clone` exists for struct `HashMap<OwnedObjectPath, HashMap<OwnedInterfaceName, HashMap<String, OwnedValue>>>`, but its trait bounds were not satisfied
  --> src/main.rs:13:30
   |
13 |     let cloned = all_objects.clone();
   |                              ^^^^^ method cannot be called due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `HashMap<OwnedInterfaceName, HashMap<std::string::String, OwnedValue>>: Clone`
           which is required by `HashMap<OwnedObjectPath, HashMap<OwnedInterfaceName, HashMap<std::string::String, OwnedValue>>>: Clone`
```

I believe this is because `OwnedValue` does not implement the `Clone` trait, providing instead a `try_clone()` method.

The [zbus::fdo::ManagedObjects](https://docs.rs/zbus/latest/zbus/fdo/type.ManagedObjects.html) is an alias to `HashMap<OwnedObjectPath, HashMap<OwnedInterfaceName, HashMap<String, OwnedValue>>>`. 

zbus version: `4.4.0`

**Comment by zeenix** [comment]
I think the solution is simple here:

* impl Clone for Value and OwnedValue
* add a warning in the impl docs that it's just `self.try_clone().unwrap()` and therefore can panic if `self` contains a file descriptor and the current process exceeds the maximum number of open file descriptors.
