### ISSUE TITLE
dbus_proxy: consider switching 'assume_defaults' default value to 'false'

### ISSUE THREAD

**Issue by zeenix** [dbus2/zbus#288]
In GitLab by @lucab on Nov 8, 2022, 17:24

This is a followup from https://gitlab.freedesktop.org/dbus/zbus/-/issues/284#note_1624111.

The patch at https://gitlab.freedesktop.org/dbus/zbus/-/merge_requests/587 is introducing a new `assume_defaults` attribute for the `dbus_proxy` macro.
For compatibility reasons, it is initially defaulting to `true` (i.e. the implicit behavior beforehand) and producing a compiler warning when omitted (and not default destination/path are provided).

On the next semver break, it would be good to consider switching the default to `assume_defaults = false` and adjust the compiler warning.

**Comment by zeenix** [comment]
@lucab Looking into this right now. Just one question: 

> and adjust the compiler warning.

what should it become? It doesn't say anything about the default. Should we just remove it now? :thinking:

**Comment by lucab** [comment]
@zeenix I don't remember exactly, but I think it was either about inverting the warning (i.e. warn if it finds an explicit `assume_defaults = false`, which is already the implicit default anyway and can be now dropped) or plainly remove it. As you prefer.

**Comment by zeenix** [comment]
Thanks. Right I don't see the point of warning for turning the implicit into explicit if it's the sane default so I'll just drop the warning. Thanks for the quick action.
