### ISSUE TITLE
Not being able to use a cfg attribute on an interface method

### ISSUE THREAD

**Issue by zeenix** [dbus2/zbus#327]
In GitLab by @brkp on Mar 24, 2023, 15:34

Hello there! I can not get the following snippet of code to compile:

```rust
struct Greeter {
    count: u64,
}

#[dbus_interface(name = "org.zbus.MyGreeter1")]
impl Greeter {
    #[cfg(target_arch = "aarch64")]
    fn function(&self) {}

    fn say_hello(&mut self, name: &str) -> String {
        self.count += 1;
        format!("Hello {}! I have been called {} times.", name, self.count)
    }
}
```

```sh
cargo build
   Compiling test v0.1.0 (/home/null/workspace/test)
error[E0599]: no method named `function` found for reference `&'call Greeter` in the current scope
  --> src/main.rs:11:8
   |
11 |     fn function(&self) {}
   |        ^^^^^^^^ method not found in `&'call Greeter`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `test` due to previous error
```

Does this mean that having cfg attributes for conditional compilation is not supported? While I acknowledge that it is preferable for the D-Bus interface you receive to be consistently stable, I would appreciate having the option.
 
Thanks for this amazing set of libraries!

**Comment by flukejones** [comment]
Hi @zeenix, sorry to resurrect an old issue but it seemed prudent to keep this particular use-case in one area.

I recently came across one are where I would have liked his ability: bluez dbus api. I'm currently working on an implementation due to a requirement at work and wanted to at-least generalise it enough to be useful outside of work. The bluez spec however contains many methods/properties marked as "experimental" and it seemed to me to be a good thing to put behind a cfg feature.

**Comment by zeenix** [comment]
@flukejones 

1. Just fyi this issue was created for `dbus_interface` and not `dbus_proxy`.
2. The API is declared experimental on the service side. Don't think it should have any bearing on the bindings (as long as it's documented clearly). cfg isn't a good way to reduce binary size nor build time (assuming only a handful of methods here).

But still I'm fine with reopening this if you can provide a PR. 👍

**Comment by flukejones** [comment]
`dbus_interface` is what I'm using as the advertising and gatt services are indeed server-side. I actually worked around it by using `#[cfg(feature=blah)` to gate an error return block ala https://github.com/dbus2/zbus/issues/448#issuecomment-1683342256 . This works fine for what I need at the moment but if I need a concrete solution as in this issue, I'll be sure to do a PR.

**Comment by zeenix** [comment]
Bumped into this myself. :)
