### ISSUE TITLE
Make Gnome (wayland) display settings persistent without asking.

### ISSUE THREAD

**Issue by VeldoraTheDragon** [dbus2/zbus#339]
Hi

I know, I can change the display settings of gnome w. wayland using d-bus.
When chaning the settings, they're not persistent and only valid for the current session.

When setting the setting persistent, Gnome asks me, if I want to keep the changes or undo them.

Is there a way, to make the settings via d-bus persistent, without having Gnome asking me, if I want to keep the changes?
Reference-Issue to gnome-randr-rust: https://github.com/maxwellainatchi/gnome-randr-rust/issues/22

Above program is a rust-software, that aims to imitate xrandr behaviour, but for gnome on wayland.

**Comment by zeenix** [comment]
> I know, I can change the display settings of gnome w. wayland using d-bus.

I won't have any clue. I'm not familiar with that service. Each service has its own API an behaviour and nothing to do with zbus itself. zbus only handles the communication/connection part.
