### ISSUE TITLE
Connect to non-standard address

### ISSUE THREAD

**Issue by qingxiang-jia** [dbus2/zbus#354]
Hi, I am trying to connect to IBus. It uses non-standard address like this:
```
unix:path=/home/lee/.cache/ibus/dbus-80D9VpWG,guid=bc3646a2dc62a1f65d29cc69646a0469
```
I have generated proxy using zbus-xmlgen. So after getting a session connection, I attempted to use the ProxyBuilder to create the proxy. I don't know if I did wrong, but I tried both ProxyBuilder.destination and ProxyBuilder.path to pass the IBus address but both failed.

I am sure this is supported and is easy to do. But I couldn't find any example or documentation on this.

Thanks!

**Comment by zeenix** [comment]
> Hi, I am trying to connect to IBus. It uses non-standard address like this:

Nothing non-standard about it actually. It's just a custom/private bus, not the session or system bus.

> I have generated proxy using zbus-xmlgen. So after getting a session connection, I attempted to use the ProxyBuilder to create the proxy.

You want to use `ConnectionBuilder::address`. Connection is what talks to the bus. This is [documented in our book](https://dbus2.github.io/zbus/connection.html#using-a-custom-bus-address) but I just realized it still talks of the old (1.0 API). Thanks to you reporting this, I have now put that on top of my todo. :)

BTW, I'd strongly recommend you to go through the book, at least the [first](https://dbus2.github.io/zbus/concepts.html) [3](https://dbus2.github.io/zbus/connection.html) [chapters](https://dbus2.github.io/zbus/client.html).

**Comment by qingxiang-jia** [comment]
Thanks for the help!
