### ISSUE TITLE
zvariant v3.14.0: test failures on big-endian s390x (s390x-unknown-linux-gnu)

### ISSUE THREAD

**Issue by decathorpe** [dbus2/zbus#358]
With the most recent release, the dev-dependency on a git snapshot of the glib crate was replaced with a normal dependency, which allowed me to run test suite of zvariant during package builds for Fedora Linux - which in turn has surfaced a few test failures on big-endian System Z (s390x).

Since s390x is the only big-endian architecture we support I can't yet tell if this is a problem that affects all big-endian architectures, or if it's specific to s390x.

This is the output (truncated to only --lib results, doc-tests all passed) from cargo test --release (with a few more distro-specific flags which should not affect results):

```
failures:
---- framing_offset_size::tests::framing_offset_size_bump stdout ----
thread 'framing_offset_size::tests::framing_offset_size_bump' panicked at 'assertion failed: `(left == right)`
  left: `U32`,
 right: `U64`', src/framing_offset_size.rs:114:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
    framing_offset_size::tests::framing_offset_size_bump
test result: FAILED. 36 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
error: test failed, to rerun pass `--lib`
```

Since s390x is a rather esoteric architecture outside IBM, it's hard for me to provide steps to reproduce this failure. Even the support for running cargo emulated on s390x is currently kind of broken due to cargo not working right in QEMU static mode 😞 But I have (limited) access to s390x hardware through Fedora server infrastructure, so at least I can submit test builds.

**Comment by zeenix** [comment]
> Since s390x is a rather esoteric architecture outside IBM, it's hard for me to provide steps to reproduce this failure.

I can imagine. This seems a much smaller issue than #357 though. I'll try to provide a fix and ask you to test it for me?

**Comment by decathorpe** [comment]
Thanks! Sure, I can submit test builds with patches applied.

**Comment by decathorpe** [comment]
It looks like the linked PR fixes many issues, but not all - two failures remain:

```
failures:
---- tests::dict_value stdout ----
[src/lib.rs:1057] encoded.len() = 40
thread 'tests::dict_value' panicked at 'no entry found for key', src/lib.rs:1077:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- tests::option_value stdout ----
thread 'tests::option_value' panicked at 'assertion failed: `(left == right)`
  left: `Some(4096)`,
 right: `Some(16)`', src/lib.rs:1610:9
failures:
    tests::dict_value
    tests::option_value
test result: FAILED. 35 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
error: test failed, to rerun pass `--lib`
```

**Comment by zeenix** [comment]
> but not all - two failures remain:

Should be fixed now.

**Comment by decathorpe** [comment]
Can confirm!
