### ISSUE TITLE
Panics when dropping a zbus stream inside tokio's `LocalSet`

### ISSUE THREAD

**Issue by acheronfail** [dbus2/zbus#380]
I've created a minimal reproducible example in a repository here: https://github.com/acheronfail/zbus-teardown.

Basically, I have a single-threaded application (running on `tokio`'s `current_thread` runtime).
Everything runs on a `LocalSet`, and when I use `zbus` to create a stream (i.e. `zbus_proxy.receive_*()` methods) if the future is dropped then a panic occurs.

From what I can tell, this occurs because:

* When `MessageStream` is dropped, it calls `conn.remove_queue_match`: https://github.com/dbus2/zbus/blob/37f59280085b9155274e0dee42aa5c6c5e77f4b7/zbus/src/message_stream.rs#LL288C13-L288C36
* When that is called, it spawns a new task to do that: https://github.com/dbus2/zbus/blob/37f59280085b9155274e0dee42aa5c6c5e77f4b7/zbus/src/connection.rs#LL1140C30-L1140C30

There's a stacktrace in the README of the linked repository with more details.

**Comment by zeenix** [comment]
Thanks so much for filing this but this is a known-issue with tokio. Currently you can only drop async instances in async context and vice-versa. We previously used `block_on` in `Drop::drop` and that lead to the opposite issue: panics and hangs if someone dropped an instance in an async context. This still [applies to the blocking wrappers](https://docs.rs/zbus/latest/zbus/blocking/index.html#caveats). The fix (or rather workaround) is simple though: use the blocking wrappers (it's free to convert between async and blocking variants).

However, if you've any ideas on how to do this better (especially w/o breaking API), I promise to give them a very serious consideration. I don't like these limitations either so I'd love to avoid them.

**Comment by zeenix** [comment]
Hmm.. one thing we could do is have `Proxy` impl [`AsyncDrop`](https://docs.rs/zbus/latest/zbus/trait.AsyncDrop.html) and then you can also do `block_on(proxy.async_drop())`.

**Comment by acheronfail** [comment]
> The fix (or rather workaround) is simple though: use the blocking wrappers (it's free to convert between async and blocking variants).

Could you elaborate on this part a little more? Do you mean - in my example - that I'd use the `NetworkManagerProxyBlocking` instead, and only be able to use it in a blocking way?

**Comment by acheronfail** [comment]
I've also been experimenting with this, and I've found some interesting behaviour!

I added this commit to the repository: https://github.com/acheronfail/zbus-teardown/commit/fae1bb8ed1705c2184b716bc18ab448f8821a447

If I use `tokio::task::spawn_local` to run the task, then the panic occurs. 
However, if I create the future manually, and then place it within a `tokio::select!` then the panic doesn't occur, and things drop properly...

Not sure if this is a `tokio`-specifc thing, or perhaps something in `zbus`...

**Comment by zeenix** [comment]
> > The fix (or rather workaround) is simple though: use the blocking wrappers (it's free to convert between async and blocking variants).
> 
> Could you elaborate on this part a little more? Do you mean - in my example - that I'd use the `NetworkManagerProxyBlocking` instead, and only be able to use it in a blocking way?

As I wrote, it's free to convert between the blocking and non-blocking variants. Also you can deref the blocking wrapper to the non-blocking variant (i-e use async API directly on the blocking wrapper). So you could either create and use `NetworkManagerProxyBlocking` or convert from `NetworkManagerProxy` to `NetworkManagerProxyBlocking` just before dropping it. There may be other ways.

> If I use tokio::task::spawn_local to run the task, then the panic occurs. 

Hmm... well zbus is using the multithreaded spawn and they're unlikely to be compatible so tokio treats them as different things.

> _However,_ if I create the future manually, and then place it within a `tokio::select!` then the panic doesn't occur,

That's expected as select is async context and all calls have access to the tokio runtime they're running in, in the context.

> Not sure if this is a `tokio`-specific thing, or perhaps something in `zbus`...

Well this is very much a tokio-specific thing and tokio doesn't make things easy for library developers if they don't want to have a hard dependency on it. However, maybe we need to add a feature(s) that makes zbus use single-thread API. It might be tricky though.

**Comment by acheronfail** [comment]
Forgive my ignorance - I believe I'm missing something obvious because I'm unsuccessful at using your mentioned workarounds.

> As I wrote, it's free to convert between the blocking and non-blocking variants. Also you can deref the blocking wrapper to the non-blocking variant (i-e use async API directly on the blocking wrapper). 

As far as I can tell with my tests, this isn't a workaround - if I use a blocking API inside of an `async` context, then tokio will panic with something along the lines of `a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.`. 

> So you could either create and use NetworkManagerProxyBlocking or convert from NetworkManagerProxy to NetworkManagerProxyBlocking just before dropping it. There may be other ways.

It seems to me that this isn't an option either, since this task is dropped at an `.await` boundary since it's being shutdown by tokio - I don't know of a way to have custom behaviour for `Drop` in which to do the conversion when it's shutdown like this.

> That's expected as select is async context and all calls have access to the tokio runtime they're running in, in the context.

As far as I understand it - _this is all running in an async context_. `tokio::task::spawn` and `tokio::task::spawn_local` both add the task to the current runtime's queue, the only visible difference is that `spawn` must be `Send` and `spawn_local` doesn't.

I don't think that `tokio::task::spawn` is "multi-threaded" per se, it's just that it enforces `Send` so it can be used in a multi-threaded runtime? Again, I'm new to async Rust, so bear with me if I've missed something obvious.

**Comment by acheronfail** [comment]
Alright, I've replicated this without `zbus` at all - and it is indeed just the call to `spawn_local` - I started a discussion with `tokio`: https://github.com/tokio-rs/tokio/discussions/5794

I'm still not sure if I can actually work around this issue, though. I'll see what the `tokio` folks have to say.

**Comment by acheronfail** [comment]
I'm happy to close this issue here in `zbus`, since I feel that the root cause of this is some behaviour I found unexpected in how `tokio`'s API handles its `Drop`s.

For any future readers, I think this explanation should suffice:

When calling `tokio::task::spawn` or `tokio::task::spawn_local` from within a struct's `Drop` implementation, there are two scenarios:

1. The value was `Drop`ped because it went out of scope - the tasks spawned in `Drop` will work as expected
2. The value was `Drop`ped because the runtime was shutting down - the tasks spawned in `Drop` may cause a panic if they are dropped before the `async` context is dropped.

In order to avoid the panic on drop, be sure to control when all the values are dropped in your runtime - here's an example which uses a `LocalSet`:

```rust
let fut = async { /* your async code */ };

// !!! This will cause panics!
runtime.block_on(
    // <-- LocalSet created here
    LocalSet::new().run_until(fut)
    // <-- Runtime::block_on runs LocalSet, and once it's finished, its async context is closed
    // <-- LocalSet dropped here, after the Runtime's async context has closed
    // !!! panics occur here because Drop's spawn tasks after async context has closed
);

// 👍 this code does not panic
runtime.block_on(
    // <-- async block created here
    async {
        // <-- LocalSet created here
        LocalSet::new().run_until(fut).await;
        // <-- LocalSet completed here after .await
    } // <-- LocalSet dropped at the end of this async block - still within Runtime::block_on's async context
    // <-- Runtime::block_on's async context is finally closed here, nothing else is dropped
);
```

**Comment by acheronfail** [comment]
> Right but as you noted yourself, it won't be as trivial as that. OTOH, it could be still trivial enough. E.g maybe all we need to do is add a tokio-multi-thread feature (enabled by default), which when disabled uses spawn_local.

I think that controlling when the values are dropped in this case is likely a better solution for `zbus`.

Though, now that I think about it, everything is torn down when the runtime is shutdown - there is no "cleanup" that occurs. :thinking: So the `async` tasks spawned in the `Drop` implementations never get run, because when shutting down `tokio` just silently ignores the calls to `task::spawn*` (i.e., it doesn't queue them on the runtime, since it's shutting down).

I wonder if there's a way we can tell `tokio` to at least run those final tasks before shutting down... I see the issues with that though - what if a `Drop` implementation spawns a task that spawns another task, and it never stops, and thus never shuts down, etc.

Either way, I think this is a discussion for `tokio`, not for `zbus`.

Thanks again for your quick responses and help!
