### ISSUE TITLE
`arg0namespace` has an overly restrictive type

### ISSUE THREAD

**Issue by MaxVerevkin** [dbus2/zbus#382]
Currently `-` is not supported in bus names:

> ```
> Err(
>     Variant(
>         Message(
>             "Invalid interface or error name: `-` character not allowed",
>         ),
>     ),
> )
> ```

Even though [the dbus spec](https://dbus.freedesktop.org/doc/dbus-specification.html#message-protocol-names-bus) does discourage the usage of `-`:

> Each element [of a bus name] must only contain the ASCII characters "[A-Z][a-z][0-9]_-", with "-" discouraged in new bus names.

I think it is overly strict and there are still apps that use `-` in their names.

Reported downstream at https://github.com/greshake/i3status-rust/issues/1914.

**Comment by MaxVerevkin** [comment]
I should note that this issue causes match rules with `arg0namespace` not match a message in which `arg0` contains `-`.

**Comment by zeenix** [comment]
> I think it is overly strict and there are still apps that use `-` in their names.

Sure. Should be quite trivial. PR? ;)

**Comment by MaxVerevkin** [comment]
> Should be quite trivial

I'm not so sure. Right now `arg0namespace` has the type of `InterfaceName` (which indeed prohibits the use of `-`) and this is part of the public API, while the spec says that `arg0namespcae` is

> Like a bus name, except that the string is not required to contain a '.' (period)

I don't know how to approach this. Ideally the type of `arg0namespace` should be changed, but this would be a breaking change.

**Comment by zeenix** [comment]
> > Should be quite trivial
> 
> I'm not so sure. Right now `arg0namespace` has the type of `InterfaceName` (which indeed prohibits the use of `-`)

Hm.. I just only noticed that we're talking `InterfaceName` as well as `BusName` here. The spec says:

> Because every valid interface name is also a valid bus name, this can also be used for messages whose first argument is an interface name.

and I had decided to use `InterfaceName` because of that but seems that's a lie if you want to be backwards compatible. :(

> > Like a bus name, except that the string is not required to contain a '.' (period)
> 
> I don't know how to approach this. Ideally the type of `arg0namespace` should be changed, but this would be a breaking change.

Indeed. The change to `MatchRuleBuilder::arg0namespace` won't be (we can provide a `TryFrom<InterfaceName> for BusName` for people who were passing `InterfaceName` rather than just a string) but `MatchRule::arg0namespace` is tricky.

**Comment by MaxVerevkin** [comment]
Apparently `BusName` does allow `-`, so the title is misleading.

**Comment by zeenix** [comment]
I think we should:

* Add `arg0ns` methods that take/give BusName.
* Internally keep a BusName instead of an InterfaceName.
* Have existing methods convert between the two types.
* Deprecate existing methods.

**Comment by MaxVerevkin** [comment]
But that would still be too restrictive: `arg0namespace='org'` is valid but would be rejected. Ideally it should be a new type.

But if we go with `BusName`, it should probably be `WellKnownName`, as `:` is not allowed in interface names.

**Comment by zeenix** [comment]
Ah true. 😞 I don't think we need a new type just for this though (unless there's any other use possible)? I'd just use a string, check that format in the builder setter and document the expected string format.

**Comment by MaxVerevkin** [comment]
> Have existing methods convert between the two types.

Again, I'm not sure how to accomplish this.  If the signature of `arg0namespace` was

```rust
pub fn arg0namespace(&self) -> Option<InterfaceName<'_>>;
```

instead of

```rust
pub fn arg0namespace(&self) -> Option<&InterfaceName<'_>>;
```

then an instance of `InterfaceName` that borrows a string from `self` can be created each time the function is called. But with the current signature `self` must contain an `InterfaceName`. Please correct me if I'm wrong.

**Comment by zeenix** [comment]
> then an instance of `InterfaceName` that borrows a string from `self` can be created each time the function is called. But with the current signature `self` must contain an `InterfaceName`. Please correct me if I'm wrong.

You're not, I just didn't remember we were returning a ref. I guess you can skip this part then and we've to keep both inside, so when builder sets one, we set both.
