### ISSUE TITLE
Error: Address("Unable to open shared memory")

### ISSUE THREAD

**Issue by divflex** [dbus2/zbus#388]
os: windows 11
rust: rustc 1.72.0-nightly (43062c43d 2023-06-09)

```
async-std = { version= "1.12.0", features=["attributes"]}
zbus ={ version = "3.13.1", features=["windows-gdbus"]}
```

Run the example server code from readme get: `Error: Address("Unable to open shared memory")`

on wsl ubuntu 22.04: 

`Error: InputOutput(Os { code: 2, kind: NotFound, message: "No such file or directory" })`

**Comment by zeenix** [comment]
You'll need to install a D-Bus broker/daemon on Windows. Only Linux has it built-in (typically). Have a look at our CI, if you want to install dbus reference impl from the source. I don't recall what the "gdbus" feature was about though but you might need to explicitly enable that during dbus build.

**Comment by zeenix** [comment]
> on wsl ubuntu 22.04:

Oh I missed that part. That's impossible. Our CI builds and runs similar tests on Ubuntu runners successfully.

Can you please paste the code?

**Comment by divflex** [comment]
> > on wsl ubuntu 22.04:
> 
> Oh I missed that part. That's impossible. Our CI builds and runs similar tests on Ubuntu runners successfully.
> 
> Can you please paste the code?

Thanks. Here is my code:

```cargo.toml
[dependencies]
tokio = {version="1.28.2", features=["rt", "macros", "rt-multi-thread"]}
zbus ={ version = "3.13.1", features=[ "tokio"]}
```

examples/server.rs
```rust
use std::{error::Error, future::pending};
use zbus::{ConnectionBuilder, dbus_interface};

struct Greeter {
    count: u64
}

#[dbus_interface(name = "org.zbus.MyGreeter1")]
impl Greeter {
    // Can be `async` as well.
    fn say_hello(&mut self, name: &str) -> String {
        self.count += 1;
        format!("Hello {}! I have been called {} times.", name, self.count)
    }
}

// Although we use `async-std` here, you can use any async runtime of choice.
#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let greeter = Greeter { count: 0 };
    let _conn = ConnectionBuilder::session()?
        .name("org.zbus.MyGreeter")?
        .serve_at("/org/zbus/MyGreeter", greeter)?
        .build()
        .await?;

    // Do other things or go to wait forever
    pending::<()>().await;

    Ok(())
}
```

**Comment by zeenix** [comment]
> Thanks. Here is my code:

I ran this verbatim in a fresh new repo/project on my Fedora and as expected, it works just fine.

Are you sure it's  full Ubuntu desktop? If not, you need to install/enable D-Bus broker then.

**Comment by zeenix** [comment]
We should make this very clear though. Not everyone listens to our advice to read our book first and just want to try it out quickly (which is very fair). I created #389 for that.

**Comment by zeenix** [comment]
> Ok. I have said it is wsl ubuntu.

Sorry, I don't know what "WSL" is. The session bus is part of a user (desktop) session. It's not run by default for remote or terminal login for example. You'll have to run/start it yourself in those cases.

> I think the broker is running?

That's the system bus and the example is for session. You could change `session` to `system` in the example but then you'll either have to run your service as root (`sudo PATH_TO_BINARY`) or install a configuration file.

For launching a session bus manually, see [here](https://manpages.ubuntu.com/manpages/focal/en/man1/dbus-launch.1.html). You can just do:

```
dbus-launch --exit-with-session cargo run
```

I strongly recommend to read our book and familiarize yourself with D-Bus concepts before trying out zbus btw. It's very short.

**Comment by divflex** [comment]
I did read the book (several times) ... thanks for you explanation.  I didn't realize that "session" means desktop session (my english is poor)... I just need ipc.

I have tried to change my code to the [p2p](https://dbus2.github.io/zbus/connection.html#peer-to-peer-connection) style and it did works. So I tried to implement the server and client this way.

But the example use `UnixStream::pair` which create server / client at the same place. I tried to create server use `UnixStream/TcpStream connect`, but it says `connection refuse` ... the `Builder` does not accept `TcpListener` either... 
i'm a bit confused... 

I tried to search examples but there aren't many...

**Comment by zeenix** [comment]
> I did read the book (several times) ... thanks for you explanation.

NP. I didn't mean to imply you didn't read. I was only making sure you did.



> I didn't realize that "session" only means desktop session (my english is poor)...

It actually doesn't. Just that a desktop session on Linux typically includes a D-Bus session for various desktop components to interact with each other. On just the terminal, it's typically not needed so it's not enabled/started automatically.

> But the example use `UnixStream::pair` which create server / client at the same place. I tried to create server use `UnixStream/TcpStream connect`, but it says `connection refuse` ... the `Builder` does not accept `TcpListener` either...
> i'm a bit confused...
 
There is [a very simple example code](https://docs.rs/tokio/latest/tokio/net/struct.UnixListener.html#examples) in tokio docs for the server side (the `stream` you get in there is what you can pass to zbus for creating a connection out of). There is also [more specific code](https://github.com/dbus2/busd/blob/main/src/bus/mod.rs) in our WIP dbus broker implementation as well. Just keep in mind that it's generic over TCP and Unix stream so you can simplify it quite a bit for your use case.

**Comment by divflex** [comment]
Thanks. I have read some of the `busd` code. I will learn `busd` when I have more time. I posted my code [here](https://github.com/divflex/learn-zbus/blob/master/examples/client.rs). 

When I run `cargo run --example client`, it says `Error: InputOutput(Custom { kind: UnexpectedEof, error: "failed to receive message" })`.   I think maybe I can fix it after try the `busd` more ... 😂

**Comment by zeenix** [comment]
You need to provide the bus address to the client too, via the environment variable mentioned in the dbus-launch docs link u shared.

Both client any service needs to be on the same bus, if they're not p2p.

**Comment by zeenix** [comment]
> With no arguments, dbus-launch will launch a session bus instance and print the address and pid of that instance to standard output.
>
>You may specify a program to be run; in this case, dbus-launch will launch a session bus instance, set the appropriate environment variables so the specified program can find the bus, and then execute the specified program, with the specified arguments. See below for examples. 

So run dbus-launch without any arguments, then export the environment variables it prints and run both service and client with that environment variable defined.

I think that should get going. Please bear in mind that while I'm trying to help, this is not a general dbus support channel. You're more than welcome to join our matrix channel and ask your questions there. There are multiple people there that might be able to help. Here, it's only me. 😊

**Comment by divflex** [comment]
It works now. Thanks for your patient...
