### ISSUE TITLE
<property>ChangedArgs is named based on D-Bus property rather than identifier name

### ISSUE THREAD

**Issue by jhenstridge** [dbus2/zbus#392]
When using zbus v3.13.1, the following code fails to compile:

```rust
#[dbus_proxy(interface = "org.freedesktop.Avahi.Server",
             default_service = "org.freedesktop.Avahi",
             default_path = "/")]
trait Server {
    #[dbus_proxy(signal)]
    fn state_changed(&self, state: i32, error: &str) -> zbus::Result<()>;
}

#[dbus_proxy(interface = "org.freedesktop.Avahi.EntryGroup",
             default_service = "org.freedesktop.Avahi")]
trait EntryGroup {
    #[dbus_proxy(signal)]
    fn state_changed(&self, state: i32, error: &str) -> zbus::Result<()>;
}
```

I get a long string of errors that start with:

```
error[E0428]: the name `StateChangedArgs` is defined multiple times
  --> src/main.rs:11:1
   |
3  | / #[dbus_proxy(interface = "org.freedesktop.Avahi.Server",
4  | |              default_service = "org.freedesktop.Avahi",
5  | |              default_path = "/")]
   | |_________________________________- previous definition of the type `StateChangedArgs` here
...
11 | / #[dbus_proxy(interface = "org.freedesktop.Avahi.EntryGroup",
12 | |              default_service = "org.freedesktop.Avahi")]
   | |________________________________________________________^ `StateChangedArgs` redefined here
   |
   = note: `StateChangedArgs` must be defined only once in the type namespace of this module
   = note: this error originates in the attribute macro `dbus_proxy` (in Nightly builds, run with -Z macro-backtrace for more info)
```

It looks like the types generated by the macro for the `org.freedesktop.Avahi.Server.StateChanged` signal are given the same names as those for the `org.freedesktop.Avahi.EntryGroup.StateChanged` signal. I can work around the problem by putting the proxies in different module namespaces, but it feels kind of awkward when I want to reference `EntryGroup` from the `Server` proxy.

**Comment by zeenix** [comment]
Hi @jhenstridge, It's pretty cool that you're using our library. I feel flattered. :)

> I can work around the problem by putting the proxies in different module namespaces, but it feels kind of awkward when I want to reference `EntryGroup` from the `Server` proxy.

That works but there is also a simpler solution: using `name` attribute of `dbus_proxy` to specify the D-Bus name while choosing a different name for the Rust method.

However if you think we can do something better here (especially w/o breaking any API), I'd seriously consider it.

**Comment by jhenstridge** [comment]
I've been attempting to convert one of my personal projects to Rust to help learn the language. I'm still picking things up.

I gave the `name` option a try by changing the second proxy definition to:

```rust
#[dbus_proxy(interface = "org.freedesktop.Avahi.EntryGroup",
             default_service = "org.freedesktop.Avahi")]
trait EntryGroup {
    #[dbus_proxy(signal, name = "StateChanged")]
    fn entry_state_changed(&self, state: i32, error: &str) -> zbus::Result<()>;
}
```

... and get the same errors about `StateChangedArgs`, etc. It seems like the names of the types are based on D-Bus signal name rather than the Rust method name, so I'm ending up with the same conflicting types.

Using `name = "StateChanged2"` gets things to compile, but watches the wrong signal name.

**Comment by zeenix** [comment]
> I've been attempting to convert one of my personal projects to Rust to help learn the language.

Cool. I'd suggest learning all the basics first though instead of doing anything specific (especially not complicated as D-Bus). I always highly recommend people to not learn Rust until they've read and understood [this awesome blog post](https://ferrous-systems.com/blog/mindsets-and-expectations/).

> ... and get the same errors about `StateChangedArgs`, etc. It seems like the names of the types are based on D-Bus signal name rather than the Rust method name, so I'm ending up with the same conflicting types.

Ah, that's indeed a bug in the macro then. The type names should be based on identifier name.

**Comment by jhenstridge** [comment]
As far as making things work automatically, one option would be to include the proxy name in the names of these ancillary types. There'd be no clash if it was `ServerStateChangedArgs` and `EntryGroupStateChangedArgs`. Or perhaps put them in a submodule namespace. I'm not really sure what would count as idiomatic at this point.

I'm not sure how that'd sit with any API stability guarantees you've given so far though: do you expect people to use these type names directly, or just rely on inference?

**Comment by zeenix** [comment]
> As far as making things work automatically, one option would be to include the proxy name in the names of these ancillary types. There'd be no clash if it was `ServerStateChangedArgs` and `EntryGroupStateChangedArgs`. Or perhaps put them in a submodule namespace. 

I don't think any of that is needed. People can always write it in modules very easily.

> I'm not really sure what would count as idiomatic at this point.

In Rust, you make use of the module system and avoid having long identifiers.

> I'm not sure how that'd sit with any API stability guarantees you've given so far though: do you expect people to use these type names directly, or just rely on inference?

I don't think what I'm proposing is a breaking change since the name attribute is only meant for controlling the underlying D-Bus name. So this is more a  fix. If people were relying on this bug, they'll unfortunately have to update their code. :(

**Comment by jhenstridge** [comment]
I guess my thoughts was that in the absence of macros, I wouldn't expect the `Server::state_changed` and `EntryGroup::state_changed` methods to conflict, so it was surprising that it expanded to code with name conflicts. It feels weird to have to rename a method to avoid a conflict with a method from a different type.

I'd put the two proxies in the same module because The Server interface has a method referencing EntryGroup:

```rust
    #[dbus_proxy(object = "EntryGroup")]
    fn entry_group_new(&self);
```

I'd left that out of the code sample in the first post, since I was trying to produce a minimal test case.

**Comment by zeenix** [comment]
> I guess my thoughts was that in the absence of macros, I wouldn't expect the `Server::state_changed` and `EntryGroup::state_changed` methods to conflict

But it's not the methods that conflict. The macro adds things and they are the ones that conflict. 

> It feels weird to have to rename a method to avoid a conflict with a method from a different type.

I agree. Perhaps you're right and we should prefix the names with the interface name. However, that would be a breaking change. :(

> I'd put the two proxies in the same module because The Server interface has a method referencing EntryGroup:

Can't you just import `EntryGroupProxy` in the other module? :thinking:

**Comment by jhenstridge** [comment]
> But it's not the methods that conflict. The macro adds things and they are the ones that conflict.

I realise that: my point was that the methods are distinct because they're namespaced by the traits, but the ancillary types conflict because they're placed in the containing module that is common to the two traits. Using the trait name to help construct the names of these ancillary types would avoid this problem.

> Can't you just import `EntryGroupProxy` in the other module? :thinking:

I mentioned in the first post that I had managed to work around the problem with submodules. I needed to import more than just EntryGroupProxy though: it needed the blocking variant too, from memory. It felt a bit weird using modules there when I didn't have any other reason to organise the code that way.

**Comment by zeenix** [comment]
> > But it's not the methods that conflict. The macro adds things and they are the ones that conflict.
> 
> I realise that: my point was that the methods are distinct because they're namespaced by the traits, but the ancillary types conflict because they're placed in the containing module that is common to the two traits. Using the trait name to help construct the names of these ancillary types would avoid this problem.

Right. I guess the solution would be to add an attribute that dictate this new behavior, to avoid breaking API.

**Comment by zeenix** [comment]
> > I realise that: my point was that the methods are distinct because they're namespaced by the traits, but the ancillary types conflict because they're placed in the containing module that is common to the two traits. Using the trait name to help construct the names of these ancillary types would avoid this problem.
> 
> Right. I guess the solution would be to add an attribute that dictate this new behavior, to avoid breaking API.

Wait, why can't you add another level of mod? So your first example here becomes:

```rust
pub mod server {
  #[dbus_proxy(interface = "org.freedesktop.Avahi.Server",
               default_service = "org.freedesktop.Avahi",
               default_path = "/")]
  trait Server {
      #[dbus_proxy(signal)]
      fn state_changed(&self, state: i32, error: &str) -> zbus::Result<()>;
  }
}

pub mod entry_group {
  #[dbus_proxy(interface = "org.freedesktop.Avahi.EntryGroup",
               default_service = "org.freedesktop.Avahi")]
  trait EntryGroup {
      #[dbus_proxy(signal)]
      fn state_changed(&self, state: i32, error: &str) -> zbus::Result<()>;
  }
}
```

Then you've no conflicts.

`dbus_proxy` macro can still provide an attribute for adding the mods for you but I don't see how that'd make anything easier for the user (assuming it's opt-in as IMO it should be).

---

I'm closing this based on those arguments but feel free to re-open if you think I'm missing something still.

**Comment by jhenstridge** [comment]
I had reduced my test case to the minimum that triggered the compilation failure. My Server trait also had the following method: 

```rust
    #[dbus_proxy(object = "EntryGroup")]
    fn entry_group_new(&self);
```

If I move the `EntryGroup` to it's own submodule, and change the annotation to `object = "entry_group::EntryGroup"`, I get a different failure:

```
error: custom attribute panicked
 --> src/mdns.rs:4:1
  |
4 | / #[dbus_proxy(interface = "org.freedesktop.Avahi.Server",
5 | |              default_service = "org.freedesktop.Avahi",
6 | |              default_path = "/")]
  | |_________________________________^
  |
  = help: message: `"entry_group::EntryGroupProxyBlocking"` is not a valid identifier
```

Presumably it is treating this as a single token rather than a namespaced identifier.

**Comment by jhenstridge** [comment]
Could you please reopen the issue? Github doesn't seem to let me reopen it after a maintainer has closed it.
