### ISSUE TITLE
Switch to syn2

### ISSUE THREAD

**Issue by bilelmoussaoui** [dbus2/zbus#401]
Currently zbus/zvariant macros still depend on syn 1.0

**Comment by zeenix** [comment]
> Currently zbus/zvariant macros still depend on syn 1.0

PR? ;)

**Comment by jplatte** [comment]
I can probably do it :)

**Comment by bilelmoussaoui** [comment]
The only missing library that pulls syn1 in gtk-rs apps is zbus_macros now
