### ISSUE TITLE
Ipv4Addr fails to serialize

### ISSUE THREAD

**Issue by timmclean** [dbus2/zbus#405]
Hello! Thanks for this great library. I was working on trying to serialize some IP addresses when I ran into this bug.

The `std::net::Ipv4Addr` type fails to serialize on zbus 3.14.1:

```rust
fn main() {
    let ctx: zvariant::EncodingContext<byteorder::LE> = zvariant::EncodingContext::new_dbus(0);

    let ip: Ipv4Addr = "8.8.8.8".parse().unwrap();
    eprintln!("{:?}", ip);
    let x_bytes = zvariant::to_bytes(ctx, &ip).unwrap();
    eprintln!("{:x?}", x_bytes);
}
```

```
8.8.8.8
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Message("invalid length 5, expected >= 6 characters")'
```

It looks like `Type` is implemented for Ipv4Addr as `<(u32, &[u8])>::signature()`. I was expecting it to be `<[u8; 4]>::signature()`, i.e. just 4 bytes on the wire.

**Comment by zeenix** [comment]
> Hello! Thanks for this great library.

Hi, glad you like it. :+1: 

> The `std::net::Ipv4Addr` type fails to serialize on zbus 3.14.1:

Your code doesn't show your assumption and actually it really should work, just like [our testcase for it](https://github.com/dbus2/zbus/blob/main/zvariant/src/lib.rs#L1797).

> It looks like `Type` is implemented for Ipv4Addr as `<(u32, &[u8])>::signature()`. I was expecting it to be `<[u8; 4]>::signature()`, i.e. just 4 bytes on the wire.

That's because we need to be able to deserialize it back into the generic `IpAddr` and we can't do that w/o encoding the variant code as well.

**Comment by zeenix** [comment]
Hmm.. looking at the code and test case again, I think the IPv4 Type impl is wrong. I'll run some tests and fix..

**Comment by timmclean** [comment]
Confirmed fixed for me on the main branch. Thanks a bunch! :smiley:

**Comment by zeenix** [comment]
Thanks for reporting and testing. You were 100% right after all. I just misread the test case at first and thought it's the same as your code.

Now I'm very sure, this was just a c&p mistake.
