### ISSUE TITLE
Ability to create 'static Proxy objects

### ISSUE THREAD

**Issue by dominickpastore** [dbus2/zbus#446]
With ZBus, Proxy implementations created with `dbus_proxy` borrow a reference to their `Connection`. This works well in most cases, but occasionally it would be useful to be able to create a Proxy object that takes ownership of a `Connection` (since `Connection`s are cheap to clone) and has 'static lifetime. This also includes when using the builder pattern.

The basic `Proxy` struct contains [`new_owned`](https://docs.rs/zbus/latest/zbus/struct.Proxy.html#method.new_owned) that seems like it would do exactly this, but there is no such method on the implementation from `dbus_proxy`, nor does the builder pattern seem to support it.

This would be useful for creating a Proxy object that can be moved into a spawned tokio task, for example. A workaround would be to pass a cloned `Connection` into the spawned task and create the Proxy inside it, but the downside of doing so is it also moves the error handling for creating the proxy object into the task, which is not always desirable.

**Comment by zeenix** [comment]
> Proxy implementations created with `dbus_proxy` borrow a reference to their `Connection`

They actually don't. They clone it for you so you don't have to do that. They only borrow references to the attributes (interface, path and destination) and if they're static, the inner lifetime of the proxy is also static.

> This would be useful for creating a Proxy object that can be moved into a spawned tokio task, for example

For sure and one of the many use cases because of which, we made `Connection` `Send+Sync`.

> With ZBus,

P.S. It's `zbus` so you can save yourself from hitting Shift key. :wink:

**Comment by dominickpastore** [comment]
Ah, I see. Looks like it was incorrect lifetime elisions that led me to believe they were borrowing the `Connection`.

The fact that the `zbus::Proxy` struct has both `new` and `new_owned` where the former takes a `&Connection` and the latter takes a `Connection` also contributed to the misunderstanding (though it sounds like that was likely another misunderstanding in itself).

Sorry about that, and thanks for the quick clarification. This will save me some trouble for sure.

**Comment by zeenix** [comment]
> The fact that the `zbus::Proxy` struct has both `new` and `new_owned` where the former takes a `&Connection` and the latter takes a `Connection` also contributed to the misunderstanding (though it sounds like that was likely another misunderstanding in itself).

Understandable. IIRC Proxy did use to keep a `&Connection` before we made Connection an owned type. That is why the lifetime specifiers are called `'c` still. I'll change those lifetimes at least.

**Comment by zeenix** [comment]
@dominickpastore  https://github.com/dbus2/zbus/pull/447/commits/4e5ceeefeccdeae8039f6bf15c5c4643bfe666ff
