### ISSUE TITLE
Guidance on manually implementing properties?

### ISSUE THREAD

**Issue by flukejones** [dbus2/zbus#448]
I'm not too sure how to explain this.. Bluez spec states that implementors are meant to expose only the properties they will use/fill in : ["Properties which are not present will not be included in the
data."](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/advertising-api.txt).

But I don't see any easy way of doing this. I can't separate the functions in to traits to impl as `zbus::Interface` can only be implemented once.

I'd be okay with listening for property requests and responding to those, but I'm unsure how to go about that either.

(10 minutes later)

Okay so bluez is asking for which properties are available like so:

```
method call time=1692332248.228712 sender=:1.2176 -> destination=:1.2186 serial=105 path=/org/bluez/testing/advertisement/5935e8220fd3461f95a73ea26b4628ef; interface=org.freedesktop.DBus.Properties; member=GetAll
   string "org.bluez.LEAdvertisement1"
method return time=1692332248.228856 sender=:1.2186 -> destination=:1.2176 serial=10 reply_serial=105
   array [
      dict entry(
         string "Data"
         variant             array [
            ]
      )
      dict entry(
         string "Timeout"
         variant             uint16 60
      )
      dict entry(
         string "MaxInterval"
         variant             uint32 1000
      )
      dict entry(
         string "LocalName"
         variant             string "Name goes here"
      )
    ...SNIP...
      dict entry(
         string "ServiceUUIDs"
         variant             array [
            ]
      )
   ]
   ```

would there be a way to adjust this list?

**Comment by flukejones** [comment]
Okay it seems I can return an error for properties I want to be unused (depending on setup and data) like:
```rust
Err(zbus::fdo::Error::UnknownProperty( "max_interval property unused".to_string()))
```

This should be good enough for now.

**Comment by zeenix** [comment]
> I can't separate the functions in to traits to impl as `zbus::Interface` can only be implemented once.

Sure but you can have separate structs that share the state.

> This should be good enough for now.

* Right. IIRC we added support for fallible properties for bluez, even though the concept breaks the spec and is a bad pattern. You can thank Marcel Holtmann for subjecting us to this pain in multiple system APIs. :(

* If nothing else, you can always get down to implementing `Interface` manually. It's not fun but zbus can't possibly make everything easy, especially dealing with non-compliant services.

**Comment by flukejones** [comment]
> > I can't separate the functions in to traits to impl as `zbus::Interface` can only be implemented once.
> 
> Sure but you can have separate structs that share the state.

Yeah doesn't work if I need the same interface address and path does it? Admittedly I've not tried different structs with same interface address + path before so I've nearly no knowledge of how that would be handled.

> > This should be good enough for now.
> 
>     * Right. IIRC we added support for fallible properties for bluez, even though the concept breaks the spec and is a bad pattern. You can thank Marcel Holtmann for subjecting us to this pain in multiple system APIs. :(

Ooof.. I'd been wondering about that. 

>     * If nothing else, you can always get down to implementing `Interface` manually. It's not fun but zbus can't possibly make everything easy, especially dealing with non-compliant services.

I was looking at doing this but I've really not much idea on where to start or what is required. An adventure for another time perhaps.

(and yes will close as resolved)

**Comment by zeenix** [comment]
> > Sure but you can have separate structs that share the state.
> 
> Yeah doesn't work if I need the same interface address and path does it?

No and even if it was possible, it would be wrong and break something for sure. :) I actually didn't realize what you meant before.

> I was looking at doing this but I've really not much idea on where to start or what is required. An adventure for another time perhaps.

Indeed, one that probably requires staring at implementation generated by `dbus_interface`. ;)

**Comment by flukejones** [comment]
> Indeed, one that probably requires staring at implementation generated by `dbus_interface`. ;)

Actually I wonder if you can answer this for me? How do I get the code generated by the derive macros? This was actually the first thing I wanted to try but I wasn't able to figure out where or how the code was generated.

**Comment by zeenix** [comment]
> How do I get the code generated by the derive macros?

`cargo-expand`

**Comment by zeenix** [comment]
@flukejones btw, consider joining [our Matrix channel](https://matrix.to/#/#zbus:matrix.org). You'll likely get your answers much quicker that way.
