### ISSUE TITLE
Document the D-Bus signature for types that zvariant can serialize

### ISSUE THREAD

**Issue by dominickpastore** [dbus2/zbus#452]
I just ran into an issue where I was getting a "No matching method found" error, and spent quite a while trying to get to the bottom of it because I could see the method was there on introspection, clear as day.

It turned out the issue is that `[i16; 4]` becomes `nnnn` in the D-Bus type system, and I expected it to become `an`. The latter, of course, is what the method required.

Converting it to a `Vec<i16>` was an easy fix once I figured that out, but it was a long journey to get there. If the D-Bus signatures for various types were documented, that would have saved a lot of grief (at least, I couldn't find anywhere that was documented when I did the original implementation).

**Comment by zeenix** [comment]
I agree this is a bit unexpected but this **is** documented in [zvariant top-level docs](https://docs.rs/zvariant/latest/zvariant/#example-code).

> Similarly, most of the container types also map nicely to the usual Rust types and collections (as can be seen in the example code above). The only note worthy exception being ARRAY type. As arrays in Rust are fixed-sized, serde treats them as tuples and so does this crate. This means they are encoded as STRUCT type of D-Bus. If you need to serialize to, or deserialize from a D-Bus array, you’ll need to use a slice (array can easily be converted to a slice), a Vec or an arrayvec::ArrayVec.

**Comment by dominickpastore** [comment]
Ah, thanks. Nonetheless, maybe it would be useful to have a table somewhere of all the types supported by zvariant and how they map to D-Bus types, and link to it in the zbus book? (Or perhaps place the table in the zbus book?)

I say that because there's really not a lot of guidance in the book about how to figure out which types are allowed/suitable for method parameters, return values, and properties. I got there eventually, but it took quite a bit of digging to figure out what parts of the API docs had the info I needed (and I ended up finding some info only outside the docs, for example that returned object paths must be `OwnedObjectPath`, not `ObjectPath`. Obvious enough after the fact, but when I was first learning zbus, it was not).

**Comment by zeenix** [comment]
> maybe it would be useful to have a table somewhere of all the types supported by zvariant and how they map to D-Bus types, and link to it in the zbus book? (Or perhaps place the table in the zbus book?)

We support almost all types that serde supports and that's a lot of them to create a table for (every now and then we've to add more and it'll be hard to keep the table up2date) but sure, we can always do better with documentation and contributions towards that are always welcome.

> I say that because there's really not a lot of guidance in the book about how to figure out which types are allowed/suitable for method parameters, return values, and properties.

Sure. As I wrote, we can always do better.

---

BTW, there is also a [Matrix channel](https://matrix.to/#/#zbus:matrix.org) where you can ask for help when you can't figure out something.

**Comment by dominickpastore** [comment]
Fair enough. If a table wouldn't work well, maybe a couple sentences in the book on where to find more info on the supported types. Or maybe it's not necessary at all. I'm certainly no expert on the subject. I just wanted to bring it up because figuring out what the parameters and return types for my `#[dbus_proxy]` trait should be turned out to be my biggest barrier to entry. But maybe that's just me.
