### ISSUE TITLE
Signals of enums with repr(u16) result in Broken Pipe error 

### ISSUE THREAD

**Issue by mmasque** [dbus2/zbus#474]
Hi, 
I'm trying to add a signal to send a struct which contains an enum. I would like the enum to be of type u16, thus I used a `repr(u16)` macro on the enum. When repeatedly sending the signal, this results in a broken pipe error. If the `repr(u16)` line is removed, both signals return with Ok(()). I then used `dbus-monitor --session` to verify the signal is correctly broadcasted.

Here's a minimal reproducible example, which breaks apparently due to the `repr(u16)`. Since I need my signal to be a struct with an `u16` enum and not the default `u32`, any pointers to what's causing this/a fix this would be appreciated. Thanks!

```rust
use serde::Serialize;
use zbus::{dbus_interface, SignalContext};
use zbus::{ConnectionBuilder, Result};
use zvariant::Type;
struct TestInterface {}

#[derive(Type, Serialize)]
#[repr(u16)]
pub enum TestEnum {
    A,
    B,
}

#[derive(Type, Serialize)]
pub struct TestStruct {
    pub payload: TestEnum,
}

#[dbus_interface(name = "org.zbus.TestInterface")]
impl TestInterface {
    /// A signal; the implementation is provided by the macro.
    #[dbus_interface(signal)]
    async fn test_signal(ctxt: &SignalContext<'_>, data: &TestStruct) -> Result<()>;
}

#[async_std::main]
async fn main() -> Result<()> {
    let greeter = TestInterface {};
    let connection = ConnectionBuilder::session()?
        .name("org.zbus.TestGreeter")?
        .serve_at("/org/zbus/TestGreeter", greeter)?
        .build()
        .await?;

    let context = SignalContext::from_parts(connection, "/org/zbus/TestGreeter".try_into()?);

    let test_struct = TestStruct {
        payload: TestEnum::A,
    };

    // This succeeds with Ok(())
    let res = TestInterface::test_signal(&context, &test_struct).await;
    println!("res: {:#?}", res);
    async_std::task::sleep(std::time::Duration::from_secs(1)).await;

    // This fails with Error: Broken Pipe (code 32)
    let res = TestInterface::test_signal(&context, &test_struct).await;
    println!("res: {:#?}", res);
    Ok(())
}

```

The above code prints out the following: 

```rust
res: Ok(
    (),
)
res: Err(
    InputOutput(
        Os {
            code: 32,
            kind: BrokenPipe,
            message: "Broken pipe",
        },
    ),
)
```

This was run on both an x86 machine running Linux as well as on an ARM machine, same error was observed.
`Cargo.toml`: 
```toml
[package]
name = "test-dbus-signal"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = {version = "1.12.0", features = ["attributes"]}
serde = {version = "1.0.188", features = ["derive"]}
zbus = "3.14.1"
zvariant = "3.15.0"
```

Rust version: `rustc 1.72.0 (5680fa18f 2023-08-23)`

**Comment by zeenix** [comment]
Firstly, thanks for the very detailed issue with a reproducer code.

> Hi, I'm trying to add a signal to send a struct which contains an enum. I would like the enum to be of type u16, thus I used a `repr(u16)` macro on the enum. When repeatedly sending the signal, this results in a broken pipe error. If the `repr(u16)` line is removed, both signals return with Ok(()). I then used `dbus-monitor --session` to verify the signal is correctly broadcasted.

I think the issue is that serde doesn't know to serialize as `u16`. You need to use `serde_repr::Serialize_repr` derive for that. zbus itself needs to encode enums as `u8` so you can look at [our code for an example](https://github.com/dbus2/zbus/blob/main/zbus/src/message/header.rs#L54).

Please do let us know if that works.

---

> zbus = "3.14.1"
> zvariant = "3.15.0"

Btw, I'd strongly suggest to use zvariant through `zbus::zvariant` to ensure it's always the one that's compatible.

**Comment by mmasque** [comment]
Hi @zeenix, I appreciate the quick response! Using `#[derive(Type, Serialize_repr)]` works, thanks! 
Perhaps this note should be added to the zvariant/zbus doc? I'm happy to PR if you have some guidance about where it is best to document it (unless I missed an existing explanation).
