### ISSUE TITLE
Remove `dbus_` prefix from macro names

### ISSUE THREAD

**Issue by zeenix** [dbus2/zbus#477]
There is no need for this prefix and there is no collision possible in `zbus_macros` nor `zbus`. 

We should definitely keep the existing names but deprecate them.

**Comment by elmarco** [comment]
I disagree with that radical approach to name and namespaces. Imho, names that are too generic aim to be prefixed, especially if they are in the root namespace. (interface, proxy, addr, handler etc)

**Comment by zeenix** [comment]
> Imho, names that are too generic aim to be prefixed,

There is no chance of collision in Rust and I don't see a chance of it causing any confusion to developer either.

Names should be descriptive but not longer than needed. Here `dbus_` prefix doesn't give us anything.

**Comment by zeenix** [comment]
Besides we've a similar thing in zvariant_derive: `Type`, `Value`, etc. are both types and derive macros on the same path. This very much consistent with the usual practices in the Rust world (e.g see `serde::{Serialize, Deserialize}`.

**Comment by elmarco** [comment]
ok.., as long as it's "natural" to simply use "zbus::proxy" etc.

**Comment by zeenix** [comment]
Since 4.0 is late by months now and this is not super important, I'm removing the 4.0 milestone from here. This will have to wait for the next API break.

**Comment by zeenix** [comment]
Actually, the main reason this hasn't happened is because we want to do it w/o breaking API so it doesn't haven to wait for 5.0. I'll remove the milestone.
