### ISSUE TITLE
Feature-gate bus implementation API

### ISSUE THREAD

**Issue by zeenix** [dbus2/zbus#480]
Typical user does not need some of the API provided for bus implementations. Let's feature-gate that so in most builds, this API is automatically removed.

**Comment by TTWNO** [comment]
Where is `bus-impl`? I'm willing to setup a PR if you can trust me not to disappear for a few days again, haha!

**Comment by zeenix** [comment]
> Where is `bus-impl`? 

The task is to add it. You'll have to search through the docs/commit history to find out API (e.g [`Connection::set_unique_name`](https://docs.rs/zbus/latest/zbus/struct.Connection.html#method.set_unique_name). It's not the best task to pick randomly, I'm afraid.

**Comment by zeenix** [comment]
4.0 is late and this isn't super important.
