### ISSUE TITLE
zvariant: Implement `PartialEq` for `Dict` that ignores the order of `entries`

### ISSUE THREAD

**Issue by mguentner** [dbus2/zbus#484]
The implemented `PartialEq` trait for a `HashMap` in `std` does not take the order into account but `zvariant::Dict` does.

Example:

```rust
let mut map1: HashMap<i32, &str> = HashMap::new();
map1.insert(1, "one");
map1.insert(2, "two");
map1.insert(3, "three");

let mut map2: HashMap<i32, &str> = HashMap::new();
map2.insert(3, "three");
map2.insert(1, "one");
map2.insert(2, "two");

assert_eq!(map1, map2); // does not panic

let dict1 = zbus::zvariant::Dict::from(map1);
let dict2 = zbus::zvariant::Dict::from(map2);

assert_eq!(dict1, dict2); // panics
```

This stems from `Dict` not implementing `PartialEq` but [using derive](https://github.com/dbus2/zbus/blob/acc34f5cbbe3e385f6e1ed2281b8f77edb23e3fa/zvariant/src/dict.rs#L18) and hence `self.entries` is compared against `other.entries` and since both of them are `Vec`, the order suddenly matters.

While this is not a problem in flat structures where `Dict` can be converted into a `HashMap` for such a comparison, it becomes one in nested structures like `HashMap<String, OwnedValue>`.

When two instances of such a `HashMap` are compared with some values being `Dict`s the equality of these `HashMap` now depends on the order in which the `Dict`s have been constructed which cannot be controlled in most cases, especially in de-serialization.

Example:

```rust
let mut nested_map1: HashMap<&str, OwnedValue> = HashMap::new();
nested_map1.insert("one", OwnedValue::from(dict1));
nested_map1.insert("two", OwnedValue::from(Value::from("foo")));

let mut nested_map2: HashMap<&str, OwnedValue> = HashMap::new();
nested_map2.insert("one", OwnedValue::from(dict2));
nested_map2.insert("two", OwnedValue::from(Value::from("foo")))
assert_eq!(nested_map1, nested_map2); // panics
```

**Comment by zeenix** [comment]
Thanks so much for the detailed report. I agree that the order should not matter in the comparison. If you could provide a PR to fix this, that would be most helpful. :pray:
