### ISSUE TITLE
How to use without async

### ISSUE THREAD

**Issue by thewh1teagle** [dbus2/zbus#486]
I have a library which needs to use `dbus`, 
the library didn't written with `async` so currenly everything is blocking.
in addition it has a `python` bindings, so converting everything to `async` is something I prefer not to do.
How can I use this library in blocking mode?
If it's not possible, maybe you have another idea?
This is my library in `Rust`: [rookie](https://github.com/thewh1teagle/rookie)
and the `dbus` function I'm trying to mimc in `Rust` is here in `Python`: [browser_cookie_3#L252](https://github.com/borisbabic/browser_cookie3/blob/master/browser_cookie3/__init__.py#L252)

**Comment by zeenix** [comment]
> How can I use this library in blocking mode?

We provide [blocking wrappers](https://docs.rs/zbus/latest/zbus/blocking/index.html) for this. Please do read the [caveats mentioned](https://docs.rs/zbus/latest/zbus/blocking/index.html#caveats).

**Comment by zeenix** [comment]
We also have a dedicated chapter for [blocking API in our book](https://dbus2.github.io/zbus/blocking.html). I'd advise you to read through the (short) book before using zbus.

**Comment by thewh1teagle** [comment]
Thank you very much!
I learned a lot from the book and it makes everything simple
