### ISSUE TITLE
Consider publishing `zbus_xml`

### ISSUE THREAD

**Issue by TTWNO** [dbus2/zbus#491]
There's a new library called [`zbus_lockstep`](https://docs.rs/zbus-lockstep/latest/zbus_lockstep/) which allows you to verify the signature of a DBus method/signal at compile time.

Right now, this crate depends on `zbus` itself, but only uses a few limited features like `xml`, and the `zvariant` subcrate.

I'd like this library to function when compiling for a WASM environment. To do so, it cannot depend on the `zbus` crate itself, but only portions which handle the types, serialization, etc.

Other sub-crates like `zvariant` and `zbus_names` are already published on crates.io; these are trivial substitutions within the code.

Would you be open to publishing the `zbus_xml` crate separately?

xref: https://github.com/odilia-app/atspi/pull/141

**Comment by zeenix** [comment]
> Would you be open to publishing the `zbus_xml` crate separately?

The plan has been to publish it as the same time as zbus 4.0. I could have published it already but it depends on zvariant 4.0 (which isn't yet ready to be published). So I'd have to ask you to be a bit patient with me. I'm hopefully done with 4.0 in a matter of weeks (at most).

**Comment by TTWNO** [comment]
> So I'd have to ask you to be a bit patient with me. 

Absolutely! Looking forward to 4.0; go zeenix!

Thank you so much for your contributions.

**Comment by zeenix** [comment]
Finally [done](https://crates.io/crates/zbus_xml). :)
