### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by VorpalBlade** [dbus2/zbus#501]
Hi,

The current release of zbus depends on nix 0.26. As I have dependencies that depend on both nix 0.26 and 0.27 this bloats my binary size. I also see that in git you have already upgraded to nix 0.27. It would be awesome if you could make a new release soon so that I don't have to have multiple versions of my dependencies.

**Comment by zeenix** [comment]
Same as for zbus, https://toot.cat/@zbus/111126407295058295
