### ISSUE TITLE
`tokio` feature is not adative; can break other code not using tokio

### ISSUE THREAD

**Issue by ids1024** [dbus2/zbus#526]
This may be a known issue with how Zbus supports multiple executors, but I don't see any issues about it.

Here's a simple test case:

```rust
fn main() {
    futures::executor::block_on(async {
        let conn = zbus::Connection::system().await.unwrap();
        let dbus = zbus::fdo::DBusProxy::new(&conn).await.unwrap();
        dbg!(dbus.list_names().await.unwrap());
    });
}
```

This works with zbus's default features, but panics with `there is no reactor running, must be called from the context of a Tokio 1.x runtime'` if the `zbus/tokio` feature is enabled. In general, feature flags should always be additive and not break things. Or problems occur when they are used in multiple places in the dependency tree.

In this case blocking APIs in zbus could just be used. For a more complicated example, try `https://github.com/AccessKit/accesskit/blob/main/platforms/winit/examples/simple.rs` but add a dependency of `zbus = { version = "3", features = ["tokio"] }`. This causes use of zbus inside accesskit to panic, unless the `accesskit/zbus` feature is enabled. This is a more practical example, since it's quite reasonable to use accesskit, which internally makes use of zbus, while also using tokio/zbus in one's own code.

I don't have a good solution for this. I guess to support multiple aync reactors in clean way, it's necessary to make every type using the reactor require a type parameter, or use dynamic dispatch. (Or maybe an enum?)

I've seen this issue before with Accesskit (I  probably should have opened an issue earlier) but double checked the behavior now since I want to solve this in Reis too.

**Comment by zeenix** [comment]
The `tokio` feature is specifically for enabling very tight integration with Tokio. Since the default async-io backend works with all runtimes (including Tokio), `tokio` feature should not be enabled unless the dependent crate is absolutely certain only Tokio will be used throughout.

Library crates should only enable it if they are tokio-specific. Otherwise they should at least leave it to the user, perhaps through features of their own (a simple proxy feature would suffice).

I wish there was a better way to support Tokio. I'm closing this because I don't think there's much zbus can do here. If you come up with some ideas, please do reopen with a comment.

**Comment by ids1024** [comment]
> Library crates should only enable it if they are tokio-specific. Otherwise they should at least leave it to the user, perhaps through features of their own (a simple proxy feature would suffice).

In this case, the issue isn't a library enabling the feature. But rather, a library *not* using the `tokio` feature that spawns zbus futures on its own executor, and breaks if the bin crate (or an other) enables the feature.

In principle, feature flags should never work this way. In practice, it may be necessary if there isn't a better solution. Maybe this concern could at least be documented in some way.

* If a library spawns zbus futures on an executor, it *must* provide a `tokio` feature to spawn them on a tokio executor, and a bin crate must enable such a feature on all dependencies, or none.
* Libraries should not by default enable the `tokio` feature of zbus, or they'll break in apps using a different executor

I guess for correct behavior with additive features, it would be correct to have a feature that forces the use of `async-io` even if the `tokio` feature is enabled. (Also relevant currently if a library for some reason wanted to use zbus with unix domain sockets on Windows). Though that could be awkward to deal with since features can disable dependencies, or a library like accesskit couldn't require that by default but then disable that feature flag when the `tokio` feature is enabled...

So yeah... this runs into limitations with how async reactors *and* cargo features work.

**Comment by notgull** [comment]
Agreeing with @ids1024 that this is somewhat of a problem. I've had to chase down bugs like this where one of my 500 dependencies enables a feature that's incompatible with the rest of the ecosystem.

Ideally `zbus` wouldn't support any executor at first, and then have separate features for `smol`'s and `tokio`'s reactors. This way `tokio` or `smol` support is something that you explicitly opt into.

Alternatively one can check the value of [`tokio::Handle::try_current`](https://docs.rs/tokio/latest/tokio/runtime/struct.Handle.html#method.try_current) and, if it's `None`, wrap the following calls in a lazily initialized `tokio` runtime running on another thread, a la [`async-compat`](https://github.com/smol-rs/async-compat).

**Comment by ids1024** [comment]
If we can detect if there's a tokio runtime available, maybe it could also dispatch to async-io instead of tokio if there isn't? Which might be better than starting a tokio runtime?  If zbus has implementations for both anyway. I haven't looked at exactly how it's implemented currently, so I don't know how difficult that would be, but that seems potentially ideal in theory.

If the default `async-io` feature is disabled, it wouldn't include that logic. And would only use `tokio`. (Assuming that feature is enabled.)

**Comment by zeenix** [comment]
> Agreeing with @ids1024 that this is somewhat of a problem. I've had to chase down bugs like this where one of my 500 dependencies enables a feature that's incompatible with the rest of the ecosystem.

I don't disagree either that the situation is far from ideal. The question is if anyone has good ideas on how to solve it.

> Ideally `zbus` wouldn't support any executor at first, 

I'm not sure what you mean by this. I've to have some of the smol-rs deps to drive the tasks. zbus 2.x didn't have tight tokio integration option. What I ended up with was tokio users yelling at me for requiring smol-rs deps that are redundant with tokio. So I put in the work and provided tighter tokio integration. 

> and then have separate features for `smol`'s and `tokio`'s reactors. This way `tokio` or `smol` support is something that you explicitly opt into.

Would be great but what do I use by default?

> Alternatively one can check the value of [`tokio::Handle::try_current`](https://docs.rs/tokio/latest/tokio/runtime/struct.Handle.html#method.try_current) and, if it's `None`, wrap the following calls in a lazily initialized `tokio` runtime running on another thread, a la [`async-compat`](https://github.com/smol-rs/async-compat).

Sure, this can be done in [our runtime abstraction](https://github.com/dbus2/zbus/blob/78dd577a2850fa5ea58710ce58717ec94971192c/zbus/src/abstractions/executor.rs#L31). We can have that struct hold a `tokio::runtime::Handle`. However, we need to ensure [other abstractions](https://github.com/dbus2/zbus/blob/8643def1da7f69934f75af267c623f700cd6431d/zbus/src/abstractions/file.rs#L21) also run their futures in tokio's runtime when tokio feature is enabled. 

> If we can detect if there's a tokio runtime available, maybe it could also dispatch to async-io instead of tokio if there isn't? Which might be better than starting a tokio runtime?

Maybe. You'll need to check. If tokio is enabled, this likely means that tokio is involved, just that our code ended up running outside a runtime. Also, you'll still need to check if `async-io` feature is enabled but if it's not, what do you do then? Might be simpler to just launch a tokio runtime.

----

Anyway, feel free to provide a PR. I can reopen once that's done.
