### ISSUE TITLE
Replace winapi with windows-sys

### ISSUE THREAD

**Issue by russellbanks** [dbus2/zbus#534]
[winapi](https://crates.io/crates/winapi) hasn't been updated in over 3 years. [windows-sys](https://crates.io/crates/windows-sys) is an official Microsoft crate that is actively maintained. I can have a go at the migration and create a pull request if this is an acceptable change.

**Comment by zeenix** [comment]
Sounds good! However, perhaps best use the high-level `windows` crate?

**Comment by russellbanks** [comment]
Unless there's anything specifically needed in the higher level crate, windows-sys is generally preferable in libraries because it has faster compile times and doesn't depend on std. Anecdotally, it's also more similar to winapi's API and has been very simple to migrate - https://github.com/hwchen/keyring-rs/pull/159.

[windows-or-windows-sys](https://kennykerr.ca/rust-getting-started/windows-or-windows-sys.html)

**Comment by zeenix** [comment]
@russellbanks thanks for explaining. Sure, let's go for `windows-sys`.

**Comment by zeenix** [comment]
> @russellbanks thanks for explaining. Sure, let's go for `windows-sys`.

@russellbanks Hi, I'm getting a [strange panic from windows-sys against nightly ](https://github.com/dbus2/busd/actions/runs/7858111371/job/21442835251?pr=37#step:5:310)([only](https://github.com/dbus2/busd/actions/runs/7863081915/job/21453281810?pr=37)) in busd tests. Looking at the [relevant code in zbus](https://github.com/dbus2/zbus/blob/af493c4a99310248e115dd3ccbd06a503444eafb/zbus/src/win32.rs#L217), I don't see what's causing it. Also, it makes me rethink using -sys crate directly.

Ideas?

**Comment by zeenix** [comment]
> @russellbanks Hi, I'm getting a [strange panic from windows-sys against nightly ](https://github.com/dbus2/busd/actions/runs/7858111371/job/21442835251?pr=37#step:5:310)([only](https://github.com/dbus2/busd/actions/runs/7863081915/job/21453281810?pr=37)) in busd tests. Looking at the [relevant code in zbus](https://github.com/dbus2/zbus/blob/af493c4a99310248e115dd3ccbd06a503444eafb/zbus/src/win32.rs#L217), I don't see what's causing it. Also, it makes me rethink using -sys crate directly.
> 
> Ideas?

[Filed an issue](https://github.com/microsoft/windows-rs/issues/2842) and I think [I found a fix.](https://github.com/dbus2/zbus/pull/586)
