### ISSUE TITLE
Support non Send+Sync interfaces

### ISSUE THREAD

**Issue by MaxVerevkin** [dbus2/zbus#537]
Currently the Interface requires Send+Sync: `pub trait Interface: Any + Send + Sync`. I wonder if it would be possible to somehow support non Send/Sync interfaces when used with single threaded executors.

**Comment by zeenix** [comment]
> I wonder if it would be possible to somehow support non Send/Sync interfaces when used with single threaded executors.

I tried but it was difficult. Perhaps it's possible with some feature flags and conditional compilation. It's out of scope for now because I won't have time for it. Please re-open if you manage to contribute a PR.

**Comment by MaxVerevkin** [comment]
> with some feature flags and conditional compilation

What about adding a second trait `InterfaceLocal` and adding `ObjectServer::at_local` + `ConnectionBuilder::serve_at_local`?

I hope I can implement something like this because using `Arc<Mutex<...>>` everywhere in a single-thread application is awkward.

**Comment by zeenix** [comment]
> > with some feature flags and conditional compilation
> 
> What about adding a second trait `InterfaceLocal` and adding `ObjectServer::at_local` + `ConnectionBuilder::serve_at_local`?

If `InterfaceLocal` can work, do we really then need a separate `Interface`?

> I hope I can implement something like this because using `Arc<Mutex<...>>` everywhere in a single-thread application is awkward.

I understand the rationale for this change and I'd be happy if you can make it work.

> > Please re-open if
> 
> I think only maintainers can reopen issues.

Good point. When there is a PR and the general approach in it looks good, I'll reopen for you (just remind me).

**Comment by MaxVerevkin** [comment]
> If InterfaceLocal can work, do we really then need a separate Interface? 🤔

Dropping `: Send` requirement is is breaking change. With tokio it will require the task to be spawned from the context of a `LocalSet`.

**Comment by MaxVerevkin** [comment]
Oh, I just realized that without `Send + Sync`, `Connection` would be `!Send + !Sync`. That's bad...

**Comment by zeenix** [comment]
> Oh, I just realized that without `Send + Sync`, `Connection` would be `!Send + !Sync`. That's bad...

I recall now that, that was the main reason to add that requirement.
