### ISSUE TITLE
dbus_proxy with DynamicType not working (requires Type to be implemented)

### ISSUE THREAD

**Issue by alexg-axis** [dbus2/zbus#542]
I'm having issues using the `dbus_proxy` macro when trying to use `DynamicType`. The trait is documented as being a solution to when a type is not known ahead of type (i.e. cannot implement `Type`). 

The error I get is the following.

```
The trait bound `Value: zvariant::Type` is not satisfied.
Required by a bound in `zbus::blocking::Proxy::<'a>::call`
```

Here's a small example of what I'm trying to do.

```rust
#[dbus_proxy(
    default_service = "com.example.Service",
    interface = "com.example.Service",
    default_path = "/com/example/Service",
    gen_async = false,
    gen_blocking = true
)]
trait Some {
    /// SomeCall.
    fn some_call(
        &self,
        some_types: HashMap<&str, Type>,
        some_values: HashMap<&str, Value>,
    ) -> zbus::Result<()>;
}
```

```rust
#[derive(Serialize, Deserialize, zvariant::Type)]
#[zvariant(signature = "s")]
enum Type {
    #[serde(rename = "VALUE_TYPE_STRING")]
    String,
    #[serde(rename = "VALUE_TYPE_INTEGER")]
    Integer,
    #[serde(rename = "VALUE_TYPE_BOOLEAN")]
    Boolean,
    #[serde(rename = "VALUE_TYPE_DOUBLE")]
    Double,
}

#[derive(Serialize, Deserialize)]
enum Value {
    String(String),
    Integer(i32),
    Boolean(bool),
    Double(f64),
}

impl DynamicType for Value {
    fn dynamic_signature(&self) -> Signature<'_> {
        match self {
            Self::String(_) => Signature::try_from("s").unwrap(),
            Self::Integer(_) => Signature::try_from("i").unwrap(),
            Self::Boolean(_) => Signature::try_from("b").unwrap(),
            Self::Double(_) => Signature::try_from("d").unwrap(),
        }
    }
}
```

The example might look a bit weird from a dbus API perspective, but it makes more sense in context, without any fields stripped out.

Without knowing too much of the internals, from an API point of view, there doesn't seem to be any reason to require `Type` over `DynamicType` in `Call`. Especially as it seems to do with deserialization, which is not used in this case.

Is there any way to facilitate such a use of zbus?

**Comment by zeenix** [comment]
Looking at the code, I think this should just work already. since [the underlying API is requiring `DynamicType`](https://docs.rs/zbus/latest/zbus/blocking/struct.Proxy.html#method.call) from input (as you already figured). I did see that `dbus_proxy` is putting the `Type` bound on generic args but in your code, you're not making use of generics so that shouldn't affect you.

Anyway, it's probably some strange bug and should be easy to fix once I figure out what is going on.

**Comment by zeenix** [comment]
> Perhaps I simplified the error too much. Here's the full output.

Thanks. This helps a lot.

> Here's the full type mentioned in the error.

It's about tuples. We've [generic impls for `Type`](https://github.com/dbus2/zbus/blob/b6e0464b2dd70b3416d7ea37380671945abf7514/zvariant/src/type.rs#L245) (which itself is [implemented for all `DynamicType`](https://github.com/dbus2/zbus/blob/b6e0464b2dd70b3416d7ea37380671945abf7514/zvariant/src/type.rs#L80) as well). However, the tuple impl for `Type` won't work here as all members are expected to implement `Type`, which your `Value` type doesn't.

I hoped the solution would be as simple as adding generic impls for `DynamicType` as well but that's not possible:

```
error[E0119]: conflicting implementations of trait `r#type::DynamicType` for type `(_,)`
   --> zvariant/src/type.rs:264:13
    |
80  | / impl<T> DynamicType for T
81  | | where
82  | |     T: Type + ?Sized,
    | |_____________________- first implementation here
...
264 | /             impl<$($name),+> DynamicType for ($($name,)+)
265 | |             where
266 | |                 $($name: DynamicType,)+
    | |_____________________________________^ conflicting implementation for `(_,)`
...
283 | / tuple_impls! {
284 | |     1 => (0 T0)
285 | |     2 => (0 T0 1 T1)
286 | |     3 => (0 T0 1 T1 2 T2)
...   |
299 | |     16 => (0 T0 1 T1 2 T2 3 T3 4 T4 5 T5 6 T6 7 T7 8 T8 9 T9 10 T10 11 T11 12 T12 13 T13 14 T14 15 T15)
300 | | }
    | |_- in this macro invocation
    |
    = note: this error originates in the macro `tuple_impls` (in Nightly builds, run with -Z macro-backtrace for more info)
```

@danieldg since you added these types, would you have any suggestion on how to best solve this?

**Comment by danieldg** [comment]
I don't think this is possible to solve without removing the `impl Type for (A,…) where A…: Type` and replacing it with an `impl DynamicType for (A,…) where A…: DynamicType`.  This is a limitation of rust generics, since you can't bound a second `DynamicType` impl on a tuple with `!(all A…:Type)` to make it not conflict.  The best solution is likely to avoid using a normal tuple here and use a tuple struct (for which there is no `Type` impl), and then impl `DynamicType` for that.  Maybe `zvariant` could add a series of tuple structs that do this, or a single wrapper like:
```rust
struct DynamicTupleHelper<T>(T);
impl<A,B> DynamicType for DynamicTupleHelper((A,B)) where A: DynamicType, B: DynamicType
impl<A,B,C> DynamicType for DynamicTupleHelper((A,B,C)) where A: DynamicType, B: DynamicType, C: DynamicType
// etc, likely done via tuple_impls!
```

**Comment by zeenix** [comment]
> Maybe `zvariant` could add a series of tuple structs that do this, or a single wrapper like:

Hmm.. perhaps that's the only thing possible but maybe a `zvariant::Structure` can be used here somehow, since it implements the dynamic traits? :thinking:

**Comment by danieldg** [comment]
Because `Structure` is dynamic at runtime, it's much less efficient (needs a new allocation, everything goes through the `Value` enum).  That might not matter very much in the end, however.

**Comment by zeenix** [comment]
> That might not matter very much in the end, however.

We're already doing a lot of allocations anyways so I don't think it'd matter much to worry about it.

**Comment by alexg-axis** [comment]
Is it feasible to work around this issue by not using `#[dbus_proxy]` or is the root cause deeper than that, so implementing the traits manually won't help either? I'm willing to have an ugly workaround for now, as long as it works. The API that the client is for in this case needs to support different types in a single field, hence the use of the enum.

**Comment by zeenix** [comment]
> Is it feasible to work around this issue by not using `#[dbus_proxy]`

Yeah but you'll also need to use a wrapper type that contains both your input HashMap params and implement DynamicType on that. I have not test this though. If the `dbus_proxy` didn't use a tuple unconditionally, you could have used this wrapper with dbus_proxy itself. That should be an easier issue to fix in dbus_proxy code though.

**Comment by zeenix** [comment]
> The API that the client is for in this case needs to support different types in a single field, hence the use of the enum.

Why not use `zvariant::*Value` though? That type is specifically for dynamic types.

**Comment by zeenix** [comment]
> > The API that the client is for in this case needs to support different types in a single field, hence the use of the enum.
> 
> Why not use `zvariant::*Value` though? That type is specifically for dynamic types.

Thinking more about this, this seems like the best way forward for you anyway. You `Value` type could be a wrapper around `zvariant::*Value` and you can ensure during (de)serialization that it only uses the few types that you want to allow.

**Comment by alexg-axis** [comment]
> > > The API that the client is for in this case needs to support different types in a single field, hence the use of the enum.
> > 
> > 
> > Why not use `zvariant::*Value` though? That type is specifically for dynamic types.
> 
> Thinking more about this, this seems like the best way forward for you anyway. Youe `Value` type could be a wrapper around `zvariant::*Value` and you can ensure during (de)serialization that it only uses the few types that you want to allow.

Thank you. I get what you mean now. For me, just moving forward, just using `zvariant::Value` is a good first step. Of course, down the road, being able to use something like the value type in my original post would provide further tools to implement various APIs. But I'm not sure how often such a use case comes up. Using a wrapper around Value is likely a good enough improvement for the time being.

I consider this solved on my end, feel free to close the issue. Thank you both for your time and assistance!

**Comment by zeenix** [comment]
> I consider this solved on my end, feel free to close the issue. Thank you both for your time and assistance!

I'm very glad to hear that my suggested alternative (it's not exactly a workaround IMO) works for you. However, I'll keep this open and see if the we can help the underlying issue somehow.

**Comment by danieldg** [comment]
Added an impl that should fix it, but haven't tested it yet.  If someone can verify it actually works I'll mark the MR as ready.

**Comment by zeenix** [comment]
> Added an impl that should fix it, but haven't tested it yet. If someone can verify it actually works I'll mark the MR as ready.

Actually we should add a test anyway (should be build-only IMO).
