### ISSUE TITLE
Make SHA1 crate dependency feature gated

### ISSUE THREAD

**Issue by hkr1990** [dbus2/zbus#543]
Zbus crate depends on a crate "SHA1" which is now flagged as "cryptographically broken" by most Rust Component governance tools in major software companies.

I see that SHA1 crate is used for DBUS_SHA1_COOKIE mechanism. I did some reading on the DBUS_SHA1_COOKIE mechanism and looks like it is only needed on legacy unix and windows systems. So, it should be possible to make the DBUS_SHA1_COOKIE feature as optional feature (gated by a feature flag). This will make zbus crate not being flagged by compliance tools and improve its adoption in production.

Thanks,
Hemendra

**Comment by zeenix** [comment]
You already filed this issue with the exact same wording and we discussed it: 

https://github.com/dbus2/zbus/discussions/530

😡

**Comment by zeenix** [comment]
Ah that was a discussion. Sorry it's hard to tell on the mobile app.

In any case, as discussed already we only want to feature gate this so the issue should reflect that IMO.

**Comment by zeenix** [comment]
@hkr1990 zbus 4 already released so you missed the train on this one, I'm afraid. :( We'll have to wait till the next API break.

**Comment by hkr1990** [comment]
Sorry about that! When is the next API break expected? Also, I was planning to add the new gating feature as `no-sha1`, so by default (when no-sha1 feature isn't specified), zbus behavior will stay compatible to zbus 4. The SHA1_COOKIE mechanism will only get disabled when client explicitly specifies `no-sha1` in their cargo.toml.

Will you still consider this behavior as API break?

**Comment by zeenix** [comment]
> When is the next API break expected?

When enough issues require API break are accumulated. :) I honestly hope it won't be anytime soon though. Every break is a burden on the users.

> Also, I was planning to add the new gating feature as `no-sha1`, so by default (when no-sha1 feature isn't specified), zbus behavior will stay compatible to zbus 4. The SHA1_COOKIE mechanism will only get disabled when client explicitly specifies `no-sha1` in their cargo.toml.

I thought of that but it will still break existing code that disables default features and rely on cookie auth (on Windows, it's currently the only authenticated mechanism you can use with tokio). This would especially apply to tokio users (I think most of our users) as they disable default features to avoid depending on a bunch of smol-rs crates.

> Will you still consider this behavior as API break?

Unfortunately, yes.

**Comment by zeenix** [comment]
Giving me thought to this, I don't think most people use cookies so even though it might break things for some people, I think it won't for most people and even for people for whom this will break, it's super easy to fix with a oneline change. So please do contribute the PR.

**Comment by hkr1990** [comment]
Sure. I will start working on it.
