### ISSUE TITLE
File descriptor leak in Connection::send_message

### ISSUE THREAD

**Issue by dreiss** [dbus2/zbus#555]
We're observing a file descriptor leak in a production service.  The required conditions seem to be:

- Peer-to-peer connection over Unix-domain sockets.
- Client makes a large (>10) batch of requests over a single socket.
- Server returns a large object to all requests at the same time.
- Client disconnects after receiving all responses.

Looking at the logs, I'm pretty sure that many tasks (one for each request) enter `Connection::send_message` around the same time (to send their replies) and some get stuck.

I've uploaded a reproducer at https://github.com/dreiss/zbus-leak-repro .  It contains both a client and server, but the client can be mostly ignored.  The bug is in the server.  To test:
- In one terminal, run `cargo run --release --  server ./repro.sock`
- In another, run `cargo run --release -- client ./repro.sock`
- Server should show the message `Timed out waiting for socket to close.`
- In the client terminal (or another), run `lsof -p $(pgrep zbus-leak-repro)` to see the "connected' socket still present, even though the client is gone.
- If you comment out the `tracing_subscriber::registry()` line, you can run the client many times, and the server will continue to leak file descriptors.

Reducing the `NUM_CALLS` or `ARG_SIZE` significantly (to 4 or 100, respectively) makes the leak go away, so this appears to be some sort of race.

I was not able to reproduce under `rr` (the record-replay debugger), but I only tried for about a minute.

**Comment by zeenix** [comment]
Hi, thanks for reporting this. Could you please see if you can reproduce the issue with the git main branch? The FD handling has changed a lot and it's safer now so hopefully issues like these are avoidable with the new API.

**Comment by dreiss** [comment]
My test program fails to repro on zbus main.  I'll try upgrading our real server and try to verify.  Thanks!

**Comment by zeenix** [comment]
> My test program fails to repro on zbus main. I'll try upgrading our real server and try to verify. Thanks!

Cool. I'm glad to hear my hard work paid off. :) I will close this but if you can reproduce still with git main, just let me know and I'll reopen.

**Comment by dreiss** [comment]
Thank you.  I was able to verify that our real server is also fixed by the upgrade.  Looking forward to the next release.  zbus has been working great for us!

**Comment by zeenix** [comment]
> Thank you.  I was able to verify that our real server is also fixed by the upgrade.

Awesome. I'm glad to hear.

> Looking forward to the next release.  zbus has been working great for us!

Cool. Please don't feel pressured but if your company can help a little, that'd be awesome: https://toot.cat/@zeenix/111765915621792763 . I can promise shoutouts on my mastodon.
