### ISSUE TITLE
⬆️ Update tokio-vsock to 0.5

### ISSUE THREAD

**Issue by zeenix** [dbus2/zbus#643]
`tokio-vsock::{ReadHalf,WriteHalf}` in 0.5 has lifetimes now and provides owned versions of them for folks who want them independent. Unless we support both 0.4 and 0.5 (ughh.), this will be an API break so likely I'll only do this at the next API break.

**Comment by zeenix** [comment]
@elmarco given that I doubt anyone uses vsock support, I've reconsidered and I'm OK with updating tokio-vsock in 4.x. Of course this depends on whether or not you can finish #846 in a timely manner (making #830 obsolete).

**Comment by plugwash** [comment]
I just patched zbus in Debian to build against tokio-vsock 0.5, our patch is at

https://salsa.debian.org/rust-team/debcargo-conf/-/blob/e09e68f2d7dcce1ab70e8d32b3224706cccbc8bb/src/zbus/debian/patches/tokio-vsock-0.5.patch

**Comment by zeenix** [comment]
Thanks. Can you create a PR for this? Theoretically this is a breaking change but i think it's safe to assume it won't actually break anything for anyone and even if it does, they'll probably want to use the latest tokio-vsock themselves.
