### ISSUE TITLE
zbus 4.0.1 property read never returns, or hangs

### ISSUE THREAD

**Issue by flukejones** [dbus2/zbus#647]
I'm having some difficulty chasing this one down. Just did an update to 4.0.1. Everythign so far is okay except property reads (writes are okay),

Server:
```rust
use zbus::fdo::Error as ZbErr;

    /// Return the current LED brightness
    #[zbus(property)]
    async fn brightness(&self) -> Result<LedBrightness, ZbErr> {
        let ctrl = self.0.lock().await;
        dbg!("I was called"); // yes this prints, the call was made
        Ok(ctrl.sysfs_node.get_brightness().map(|n| n.into())?) // but never returns???
    }

    /// Set the keyboard brightness level (0-3)
    #[zbus(property)]
    async fn set_brightness(&mut self, brightness: LedBrightness) -> Result<(), ZbErr> {
        let ctrl = self.0.lock().await;
        Ok(ctrl.sysfs_node.set_brightness(brightness.into())?)
    }
```

Interface example:
```rust
    /// Brightness property
    #[zbus(property)]
    fn brightness(&self) -> zbus::Result<LedBrightness>;
    #[zbus(property)]
    fn set_brightness(&self, value: LedBrightness) -> zbus::Result<()>;
```

What xml gen gives (and I update, this also doesn't read):
```rust
    /// Brightness property
    #[zbus(property)]
    fn brightness(&self) -> zbus::Result<u32>;
    #[zbus(property)]
    fn set_brightness(&self, value: u32) -> zbus::Result<()>;
```

I've used D-Feet to read all properties fine. So the server at least is fully functional. It is only the client side that is an issue, and only with reads.

The absolute minimum in an example main():
```rust
    let conn = zbus::blocking::Connection::system().unwrap();
    let a = rog_dbus::zbus_aura::AuraProxyBlocking::new(&conn).unwrap(); // from xml gen
    dbg!(a.set_brightness(rog_aura::LedBrightness::Low).unwrap());
    dbg!(a.brightness().unwrap()); // hung here
```

I'm not sure what other info I can give here.

**Comment by flukejones** [comment]
One other tidbit: a client using zbus 3.15 can read the properties. So the issue lies in 4.0.1 somewhere.

**Comment by zeenix** [comment]
So far I'm unable to reproduce this but I'm going to keep trying. One thing though: please make sure you're not using the blocking proxy calls from an async context (and by that I don't just mean the immediate context but the whole stack). That can easily get you into hangs (with tokio, you'd get a panic but not with all runtimes).

**Comment by flukejones** [comment]
@zeenix thank you for trying. I think I have to examine the context in calling things from. I'll report back when I figure out what is causing it.

**Comment by flukejones** [comment]
Umm okay, I removed my `Cargo.lock` and regenerated. The key difference is this:

```
diff --git a/Cargo.lock b/Cargo.lock
index 2fd52db9511a..f6601045bd83 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -225,18 +225,16 @@ dependencies = [
 
 [[package]]
 name = "async-executor"
-version = "1.9.0"
+version = "1.8.0"
 source = "registry+https://github.com/rust-lang/crates.io-index"
-checksum = "601848938f6e24595d8f63bd4c4e98ed905a3bfa832743c7b8298a73d1b0517b"
+checksum = "17ae5ebefcc48e7452b4987947920dac9450be1110cadf34d1b8c116bdbaf97c"
 dependencies = [
  "async-lock 3.3.0",
  "async-task",
- "atomic-waker",
  "concurrent-queue",
  "fastrand 2.0.1",
  "futures-lite 2.2.0",
  "slab",
- "thread_local",
 ]
 ```
 
 And with that, the issue is solved. I'm not sure where 1.9.0 came from here.

**Comment by zeenix** [comment]
@flukejones thanks for letting me know. :)
