### ISSUE TITLE
`dbus_interface` macro should allow returning pre-serialized response body

### ISSUE THREAD

**Issue by zeenix** [dbus2/zbus#67]
Sometimes, you don't have ownership of the data you want to send in response to a method call so we need something like this so user don't have to clone/copy data needlessly.

@Cogitri already bumped into [this issue](https://github.com/Cogitri/zbus-lifetime/blob/0a73e4b5374463a59c6694225df7f972b7e010e6/src/main.rs). They were able to workaround the issue using `Rc` (right?) but fact remains that this should be easily possible.

I think I have a solution in mind: Add an attribute for "this method returns serialized response body":

```rust
#[dbus_interface(name = "org.myservice.Example")]
impl Example {
     #[dbus_interface(return = "serialized")]
     fn some_method(&self) -> Vec<u8> {
         ...
     }
}
```

The return type doesn't have to be fixed to `Vec` though. We could expect it to be anything `AsRef<&[u8]>` for example.

**Comment by zeenix** [comment]
@Cogitri afaik `interface` macro can handle returning reference types for a long while now. I think that was the usecase anyway? Can I close this?

**Comment by Cogitri** [comment]
Yup, thanks :)
