### ISSUE TITLE
zvariant: Better document serde_repr need with `repr`

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [dbus2/zbus#686]
Minimal repro: https://github.com/ChocolateLoverRaj/zbus/blob/297e92097f818a56580a1ab1f48f2548a65b0cf8/zbus/examples/return_enum.rs

What happens:
If I return a string or other "standard" type, the function works as expected. If I use an enum and I call
```
busctl --user call org.zbus.ReturnEnum /org/zbus/ReturnEnum org.zbus.ReturnEnum GetSomething 
```
I get the error
```
Call failed: Remote peer disconnected
```
It seems like the interface just stops because if I call it again I get the error
```
Call failed: The name is not activatable
```

**Comment by zeenix** [comment]
Hmm.. this is very strange. I minimized the example a bit more:

```rust
use serde::{Deserialize, Serialize};
use zbus::{connection::Builder, interface, Result, zvariant::Type};

#[derive(Deserialize, Serialize, Type, Debug)]
#[repr(u8)]
enum ExampleEnum {
    A = 0,
}

struct ReturnEnum;

#[interface(name = "org.zbus.ReturnEnum")]
impl ReturnEnum {
    async fn get_something(
        &self
    ) -> ExampleEnum {
        ExampleEnum::A
    }   
}

#[async_std::main]
async fn main() -> Result<()> {
    let _connection = Builder::session()?
        .name("org.zbus.ReturnEnum")?
        .serve_at("/org/zbus/ReturnEnum", ReturnEnum)?
        .build()
        .await?;

    std::future::pending::<()>().await;

    Ok(())
}
```

**Comment by zeenix** [comment]
Ah I know the problem. You're not telling serde about the representation you want. You need to [use `serde_repr`](https://docs.rs/serde_repr/latest/serde_repr/).

We need to do a better job of documenting this [here](https://docs.rs/zvariant/latest/zvariant/#example-code).

**Comment by ChocolateLoverRaj** [comment]
Just from removing the line
```rs
#[repr(u8)]
```
the example works. I didn't use `serde_repr`.

**Comment by zeenix** [comment]
> the example works.

Yes but it's now a `u32`, which might be fine for your case but it won't be for all.

> I didn't use `serde_repr`.

That's only needed when using `repr` attribute.

**Comment by jonathanhood** [comment]
I can pick this one up on the morning. I also noticed this today and didn't realize the need for an extra library here.
