### ISSUE TITLE
Introspect stops working after calling `let mut iface = iface_ref.get_mut().await;`

### ISSUE THREAD

**Issue by petewasher-flybrid** [dbus2/zbus#693]
Hello,
I followed the example to get the MyGreeter server working. It works as expected. I then wanted to extend this to allow the update of a parameter using the documented interface reference flow. 

My full code is:

```rust
use std::{error::Error, future::pending};
use zbus::{connection, interface};

struct Greeter {
    count: u64
}

#[interface(name = "org.zbus.MyGreeter1")]
impl Greeter {
    // Can be `async` as well.
    fn say_hello(&mut self, name: &str) -> String {
        self.count += 1;
        format!("Hello {}! I have been called {} times.", name, self.count)
    }
}

// Although we use `async-std` here, you can use any async runtime of choice.
#[async_std::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let greeter = Greeter { count: 0 };
    let _conn = connection::Builder::session()?
        .name("org.zbus.MyGreeter")?
        .serve_at("/org/zbus/MyGreeter", greeter)?
        .build()
        .await?;

    let iface_ref = _conn.object_server().interface::<_, Greeter>("/org/zbus/MyGreeter").await?;
    let mut iface = iface_ref.get_mut().await;
    iface.count = 0;

    // Do other things or go to wait forever
    pending::<()>().await;

    Ok(())
}
```

I am sending the call:
```
busctl --user introspect org.zbus.MyGreeter /org/zbus/MyGreeter

Failed to introspect object /org/zbus/MyGreeter of service org.zbus.MyGreeter: Connection timed out
```

Removing these lines allows the `introspect` command to work again.
```rust
    let iface_ref = _conn.object_server().interface::<_, Greeter>("/org/zbus/MyGreeter").await?;
    let mut iface = iface_ref.get_mut().await;
    iface.count = 0;
```

And if the `pending::<()>().await;` is moved above `let mut iface...`, then the introspect call works as expected.

Is this something I'm doing wrong? Thanks!

**Comment by zeenix** [comment]
> ```rust
>  let iface_ref = _conn.object_server().interface::<_, Greeter>("/org/zbus/MyGreeter").await?;
>     let mut iface = iface_ref.get_mut().await;
>     iface.count = 0;
> ```

If you keep a mutable reference to the interface around, the ObjectServer is unable get a reference to it (internally it's done through locks) and ends up waiting forever. As documented [here](https://dbus2.github.io/zbus/faq.html#im-experiencing-hangs-what-could-be-wrong), you must not keep the mutable reference around longer then you need to.

> Is this something I'm doing wrong?

Yeah but don't worry about it. You're not the first one to make it and you won't be the last. :)

**Comment by zeenix** [comment]
BTW, https://docs.rs/zbus/latest/zbus/object_server/struct.InterfaceRef.html#method.get_mut also warns about this. You just have to add an explicit drop after you're done with `iface`:

```rust
    let iface_ref = _conn.object_server().interface::<_, Greeter>("/org/zbus/MyGreeter").await?;
    let mut iface = iface_ref.get_mut().await;
    iface.count = 0;
    drop(iface);
```

or just put a scope around it:

```rust
{
    let iface_ref = _conn.object_server().interface::<_, Greeter>("/org/zbus/MyGreeter").await?;
    let mut iface = iface_ref.get_mut().await;
    iface.count = 0;
}
```

**Comment by petewasher-flybrid** [comment]
Thanks for your quick response - appreciate it!
Your suggestion resolves my issue.
