### ISSUE TITLE
Struct fields with variant type signature serialized as concrete types

### ISSUE THREAD

**Issue by jonathanhood** [dbus2/zbus#743]
When serializing struct members the zvariant serializer doesn't properly check if a member should be serialized as a variant with a type signature or as just the basic type.

## Reproduction

```rust
use serde::{ Deserialize, Serialize};
use zvariant::{serialized::Context, Type};

#[derive(Serialize, Deserialize, Type, Debug)]
#[zvariant(signature = "(vv)")]
struct VariantMembers {
    a: i32,
    b: i32
}

#[derive(Serialize, Deserialize, Type, Debug)]
#[zvariant(signature = "(ii)")]
struct ConcreteMembers {
    a: i32,
    b: i32
}

fn main() {
    let input = VariantMembers { a: 1, b: 2 };

    let context = Context::new_dbus(zvariant::Endian::Little, 0);
    let serialized = zvariant::to_bytes(context, &input).unwrap();
    let (deserialized, _): (ConcreteMembers, usize) = serialized.deserialize().unwrap();

    println!("Deserialized: {:?}", deserialized);
}
```

## Expected Outcome

The program should fail (at the `deserialize().unwrap()` call) since a struct of type `(vv)` cannot be decoded as a struct of type `(ii)`.

## Actual Behavior

The struct with type signature `(vv)` is actually encoded as a struct with type `(ii)`. Since this is the case - the program does not fail and it outputs:

```
Deserialized: ConcreteMembers { a: 1, b: 2 }
```

## Proposed Resolution

Add a peek at the type signature when serde calls serialization methods for primitive types and:
- If the type signature doesn't match (e.g. encoding a string `s` when the type signature `i`) then fail in some well defined / debuggable way.
- If the type signature is for for a variant `v` type - encode accordingly.
- If the type signature is for a concrete type that matches the call - encode encodring.

**Comment by jonathanhood** [comment]
While working on this issue I stumbled onto #749. These two issues aren't directly related - but _in code_ they end up interacting for various reasons. I'll solve that issue first and then return to this one.

**Comment by zeenix** [comment]
In general, the custom signature is only for special cases where `Type` can't be used. It's a bit like `unsafe` keyword and you're on your own if you use it. 

However, the dict type is an exception. It would be great to support that without our special derive macros indeed. So if this can be supported as a side-effect of (or rather a step towards) #746, then let's do it.

**Comment by jonathanhood** [comment]
I've raised #776 as the smallest possible increment towards this goal to get some feedback. Assuming that approach seems OK - I'll continue with raising a larger PR.

**Comment by zeenix** [comment]
> I've raised #776 as the smallest possible increment towards this goal to get some feedback. Assuming that approach seems OK - I'll continue with raising a larger PR.

I'm not sure I understand. As I wrote on Matrix, I don't mind incremental work and splitting a bigger issue into multiple smaller issues. However, I'd prefer each issue and PR to be useful on its own. If that means bigger PR, that's OK. It's the commits that should be atomic.

**Comment by zeenix** [comment]
Giving up on this as @jonathanhood is no longer interested in working on this.
