### ISSUE TITLE
GVariant always deserializes empty strings from `a{sv}` types

### ISSUE THREAD

**Issue by jonathanhood** [dbus2/zbus#744]
When using gvariant to serialize a struct with a string field it seems that the string never "makes it" into the serialized output. Upon inspection on a debugger it appears that the the serialization of the string gets sort circuited by some special case logic in the serializer [here](https://github.com/dbus2/zbus/blob/d30a1330bf117b31dc23de14a97e665444212d1d/zvariant/src/gvariant/ser.rs#L170-L175).

## Reproduction

```rust
use serde::{ Deserialize, Serialize};
use zvariant::{serialized::Context, Type};

#[derive(Serialize, Deserialize, Type, Debug)]
#[zvariant(signature = "a{sv}")]
struct TestStruct {
    a: i32,
    b: String
}

fn main() {
    let input = TestStruct { a: 1, b: "Hello World".to_string() };

    let context = Context::new_gvariant(zvariant::Endian::Little, 0);
    let serialized = zvariant::to_bytes(context, &input).unwrap();
    let (deserialized, _): (TestStruct, usize) = serialized.deserialize().unwrap();

    println!("Deserialized: {:?}", deserialized);
}
```

## Expected Outcome

The program should output:

```
Deserialized: TestStruct { a: 1, b: "Hello World" }
```

## Actual Behavior

The program outputs:

```
Deserialized: TestStruct { a: 1, b: "" }
```

## Proposed Resolution

Figure out the need for the short circuit logic there and somehow accommodate that need while still allowing strings to be serialized as variants.

**Comment by zeenix** [comment]
Is this really gvariant-specific?

**Comment by jonathanhood** [comment]
> Is this really gvariant-specific?

You may have meant "is this really gvariant specific in the spec?" and to that end, I'm not sure. I need to review the gvariant side again and get more familiar with that spec. Will definitely need research and review here before proceeding.

**Comment by zeenix** [comment]
> You may have meant "is this really gvariant specific in the spec?"

Not really. :) This looks like a very serious bug, even though I don't know any users of gvariant format.

**Comment by zeenix** [comment]
> This looks like a very serious bug, even though I don't know any users of gvariant format.

Actually, no. This is just another part of #746.

**Comment by zeenix** [comment]
> > This looks like a very serious bug, even though I don't know any users of gvariant format.
> 
> Actually, no. This is just another part of #746.

Having said that, I don't think the solution to this would be useful on its own. Hence I don't think this should be a separate issue.

**Comment by zeenix** [comment]
Closing. Let me know if you disagree.
