### ISSUE TITLE
GVariant encodes string identifiers with DBus encoding

### ISSUE THREAD

**Issue by jonathanhood** [dbus2/zbus#745]
A hashmap as a struct member seems to confuse the gvariant encoder leading to a panic when. This only happens when attempting to encode a dictionary type and not with struct types of the form `(a{ss})`. 

I currently suspect that the culprit is that `deserialize_identifier` calls into the dbus serializer [here](https://github.com/dbus2/zbus/blob/d30a1330bf117b31dc23de14a97e665444212d1d/zvariant/src/gvariant/de.rs#L124) for an implementation rather than implementing that aspect itself. This means the dbus implementation of `encode_str` is called rather than the gvariant one during deserialization - leading to the panic due to format differences.

## Reproduction

```rust
use std::collections::HashMap;
use serde::{ Deserialize, Serialize};
use zvariant::{serialized::Context, Type};

#[derive(Serialize, Deserialize, Type, Debug)]
#[zvariant(signature = "a{sa{ss}}")]
struct TestStruct {
    internal: HashMap<String, String>,
}

fn main() {
    let input = TestStruct { internal: HashMap::from([
        ("key1".to_string(), "value1".to_string()),
        ("key2".to_string(), "value2".to_string())
    ])};

    let context = Context::new_gvariant(zvariant::Endian::Little, 0);
    let serialized = zvariant::to_bytes(context, &input).unwrap();
    let (deserialized, _): (TestStruct, usize) = serialized.deserialize().unwrap();

    println!("Deserialized: {:?}", deserialized);
}
```

## Expected Outcome

The program outputs:

```
Deserialized: TestStruct { internal: {"key1": "value1", "key2": "value2"} }
```

## Actual Behavior

The program panics with the output:

```
thread 'main' panicked at src/main.rs:19:75:
called `Result::unwrap()` on an `Err` value: Message("invalid length 24, expected >= 830039407")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Proposed Resolution

Implement `deserialize_identifier` separately for the gvariant implementation.

**Comment by jonathanhood** [comment]
It also appears that the way strings are being deserialized under gvariant, specifically, is also buggy. The relevant code is [here](https://github.com/dbus2/zbus/blob/main/zvariant/src/gvariant/de.rs#L150-L184) and, in particular, it expects the slice being parsed to be a complete string terminated with null (due to the call to `from_bytes_with_nul`) where it should probably stop on the _first_ null (by using `from_bytes_until_null`).

Unfortunately, that quick fix breaks detection of bad interior nulls. Doing all of that validation requires properly processing the relevant [framing offsets](https://developer.gnome.org/documentation/specifications/gvariant-specification-1.0.html#framing-offsets) and then using that information to compute relevant boundaries and check for extraneous nulls.

**Comment by jonathanhood** [comment]
This ends up happening when `ArrayDeserializer::next_key_seed` ends up calling `serialize` [here](https://github.com/dbus2/zbus/blob/e407016636e8a828067c8d3b463672a46ad01cbc/zvariant/src/gvariant/de.rs#L612). An array of dict entries gets passed down as a slice including the trailing bytes which indicate the start offsets of each entry.  This leads to weird behavior later down the line since `deserialize_str` is expecting a slice ending in a null character representing - essentially - the first key of the first dict.

I'm not sure what the right fix is, but it's more symptoms of handling dicts being a new / largely unhandled concern for this code.

**Comment by zeenix** [comment]
While the motivation here was noble, to allow direct ser/de of structs as hashmaps, I seriously doubt this can possibly work due to incompatibilities between D-Bus format and serde's very generic API.

I wanted to be proven wrong by @jonathanhood but seems he has given up on the dream so I'll follow suit.
