### ISSUE TITLE
zbus 4.2.0: unknown interface 'org.freedesktop.DBus.Introspectable'

### ISSUE THREAD

**Issue by mmstick** [dbus2/zbus#764]
After updating from zbus 4.1.2 to 4.2.0, I'm unable to access the  `org.freedesktop.DBus.Introspectable` interface of my system service, which is using the `zbus::interface` derive macro. Calling methods directly otherwise works. Currently testing within an Ubuntu 24.04 VM.

**Comment by mmstick** [comment]
I can try when I have time. You can build the `zbus-4.2.0` branch of [system76-power](https://github.com/pop-os/system76-power) to replicate the exact issue. Though I ultimately had to downgrade to 3.15.2 because property getters in gnome-shell's GJS dbus proxy fail with `null` for some reason. Screenshot from `d-feet`

![screenshot-2024-05-02-15-13-57](https://github.com/dbus2/zbus/assets/4143535/14340d58-729d-4df4-a47f-4cabf4e03e8f)

**Comment by zeenix** [comment]
@mmstick Thanks. I feel like the properties issue is separate from introspection issue? If so, please open another issue for properties.

**Comment by zeenix** [comment]
I tried to reproduce the issue with a minimal reproducer:

```rust
use std::{error::Error, future::pending};
use zbus::{connection, interface};

struct Greeter {
    count: u64 
}

#[interface(name = "org.zbus.MyGreeter1")]
impl Greeter {
    // Can be `async` as well.
    fn say_hello(&mut self, name: &str) -> String {
        self.count += 1;
        format!("Hello {}! I have been called {} times.", name, self.count)
    }   

    #[zbus(property)]
    async fn active_profile(&self) -> &str {
        "power-saver"
    }   

    #[zbus(property)]
    async fn set_active_profile(&mut self, profile: &str) {
        println!("Setting active profile to: {}", profile);
    }   
}

// Although we use `async-std` here, you can use any async runtime of choice.
#[async_std::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let greeter = Greeter { count: 0 };
    let _conn = connection::Builder::session()?
        .name("org.zbus.MyGreeter")?
        .serve_at("/org/zbus/MyGreeter", greeter)?
        .build()
        .await?;

    // Do other things or go to wait forever
    pending::<()>().await;

    Ok(())
}
```

but I can't produce either of your issues.  Both D-feet and busctl are able to get the introspection data just fine.

I'm closing this but if you can provide a reproducer (I'm sorry but I'm not replacing a system service, just for this), I'll very gladly reopen and do my best to solve it ASAP.

**Comment by zeenix** [comment]
> Then I do not know what to do other than for COSMIC to stick to 3.15.2 for the time being. It will be a while before I have some free time to experiment with bisecting the zbus crate.

You could provide a gjs script to reproduce it so I can tell/verify.

**Comment by mmstick** [comment]
The issue here isn't with gjs or gnome-shell, but that the dbus server does not expose `org.freedesktop.DBus.Introspectable` or `org.freedesktop.DBus.Properties` with zbus 4.2.0.

```
$ busctl --system get-property net.hadess.PowerProfiles /net/hadess/PowerProfiles net.hadess.PowerProfiles ActiveProfile
Failed to get property ActiveProfile on interface net.hadess.PowerProfiles: Unknown interface 'org.freedesktop.DBus.Properties'
```

These interfaces work fine if the only change I make is setting the zbus version to `=4.1.2`.

```
$ busctl --system get-property net.hadess.PowerProfiles /net/hadess/PowerProfiles net.hadess.PowerProfiles ActiveProfile
s "balanced"
```

**Comment by zeenix** [comment]
I'm confused even more now. I thought you said that things work with busctl. 

In this case, it shouldn't be hard to provide a minimal reproducer. As I pointed out in the comment above, the minimal reproducer i came up with, doesn't have this issue at all and given our extensive tests, it's super unlikely that such a basic feature will be broken without our knowledge.

4.0 was released months ago and many folks have successfully ported their code by now, which makes it even more unlikely this is a zbus regression.

Still, I'd be happy to reconsider if provided a reproducer.

**Comment by mmstick** [comment]
You're thinking of the other issue that I'm having with all versions of 4.x.x. I was not able to test if 4.2.0 was affected by the issue because I can't access the freedesktop dbus APIs at all.

I'm in the process of porting system76-power from dbus to zbus at this very moment, so I didn't report an issue an before because we hadn't yet ported to zbus yet.

**Comment by zeenix** [comment]
> I'm in the process of porting system76-power from dbus to zbus at this very moment, so I didn't report an issue an before because we hadn't yet ported to zbus yet. All of our other services are still using zbus 3.15.2.

Thanks for doing that work and please don't misunderstand me. I'm not blaming you for being late. I was just pointing out that many others have ported and tested already, which combined with other facts, makes me think that this is likely some issue elsewhere. 

As you must have noticed already, the 4.x API is different from 3.x so there's a chance you missed something?

Can you please check if you can reproduce any of these issues on your system with the minimal reproducer code i wrote?

**Comment by zeenix** [comment]
Oh and btw, is there any chance Flatpak is involved here? Another person reported some very strange issue but that one is specific to Flatpak.

**Comment by mmstick** [comment]
No, the system76-power daemon is a system service that's only used by the desktop environment's power panel menu, the desktop environment's display and power settings pages, and through the daemon's own command line arguments. It provides both power profiles and hybrid graphics switching capabilities to a wide range of hardware in a vendor and desktop-neutral manner.

Although GNOME's power profiles daemon was inspired by system76-power, it doesn't provide the full feature set of system76-power, such as the graphics switching features or display hotplug signals. And because System76 sells a lot of laptops with hybrid graphics, it's necessary to provide those capabilities out of the box in the Ubuntu and Pop!_OS  images that come preinstalled on them. A lot of customers install other distributions as well, so you can typically find system76-power in the system repositories of most Linux distributions.

The need to switch from dbus to zbus is long overdue, but this was the best time to do it. The dbus crate was never easy to work with, and its dependencies have some vulnerabilities. We already use zbus everywhere throughout COSMIC, so it would be easier to maintain by consolidating with zbus across the board. And although system76-power is natively integrated into COSMIC, we still want to produce Ubuntu 24.04 images as an option for customers. And to do this without requiring to maintain gnome-shell extensions means restructuring our DBus server logic to offer not only `com.system76.PowerDaemon`, but to also simultaneously export the `net.hadess.PowerProfiles` and `org.freedesktop.UPower.PowerProfiles` interfaces that wrap `com.system76.PowerDaemon` and thus keep their state in sync.

When we created system76-power several years ago, there was a battery life epidemic on laptops that featured switchable graphics. NVIDIA's hardware at the time consumed a lot of energy even if it was not in use. So we were able to defeat Windows in battery life and extend it a few hours by offering an integrated graphics mode which disables the nvidia drivers in the initramfs, and then sends signals to the kernel on boot to power off its PCIe devices. We also have a lot of customers who use their dGPU exclusively for CUDA compute, so a compute graphics mode was added to make the dGPU inaccessible to the compositor, but accessible for compute applications. The display hotplug signals come in handy when the user tries to connect a display to a video output port that's hardwired to the disabled dGPU. The desktop environment can listen to this and present a notification that they need to switch to hybrid or discrete graphics mode.

**Comment by deifactor** [comment]
I was able to reproduce the failure using the example program provided above by building with `--release`; introspection fails. Dev builds don't trigger the issue. This is with zbus 4.2.0. Downgrading to 4.1.2 fixes it.

**Comment by zeenix** [comment]
> I was able to reproduce the failure using the example program provided above by building with `--release`

This is the key, thanks so much. With `--release` 2 of our tests fail (including the e2e test I mentioned above) with the same error. Now I've a way to reproduce this and will try to fix it ASAP.

**Comment by zeenix** [comment]
I did some bisecting (before even getting breakfast :crying_cat_face:) and found that 7fc3ab7b8f69e21822a0d569222baba4b72de13f is the culprit. @elmarco Please provide a fix ASAP.
