### ISSUE TITLE
zbus 4.x.x: getting a property from a GJS DBus proxy client in gnome-shell returns `null`

### ISSUE THREAD

**Issue by mmstick** [dbus2/zbus#765]
[system76-power](https://github.com/pop-os/system76-power) provides a drop-in replacement for `net.hadess.PowerProfiles` for integration with gnome-shell 46. Strangely, when gnome-shell gets the `ActiveProfile` property [here](https://github.com/GNOME/gnome-shell/blob/main/js/ui/status/powerProfiles.js#L107), the value that it receives is `null`. Despite that, gnome-shell is able to correctly set the `ActiveProfile` property. When I add logs to the `net.hadess.PowerProfiles` daemon implementation, it does show that it's returning this value as requested by gnome-shell. And if I add logs directly to gnome-shell, it seems that `ActiveProfile` returns `null` everywhere except immediately after setting to `ActiveProfile`, where it will revert back to `null` when the scope that set the property ends.

Yet if I run `busctl --system get-property net.hadess.PowerProfiles /net/hadess/PowerProfiles net.hadess.PowerProfiles ActiveProfile`, it correctly returns the value. The power settings page in GNOME Settings also correctly gets the value. So there may be some quirk in the GJS DBus proxy client implementation.

Can test with system76-power using zbus 4.1.2 from the `zbus-4.1.2` branch [here](https://github.com/pop-os/system76-power/tree/zbus-4.1.2). With zbus 3.15.2, there is no issue in getting a property from gnome-shell's gjs dbus proxy clients.

**Comment by zeenix** [comment]
Could you please provide the gjs code/command I can use to reproduce this issue? As I wrote in #764, it's unlikely a zbus issue (maybe it is or maybe somehow it wasn't reproducible with previous version of zbus).

**Comment by mmstick** [comment]
It is linked above here: https://github.com/GNOME/gnome-shell/blob/main/js/ui/status/powerProfiles.js#L107

**Comment by mmstick** [comment]
It works fine with zbus 3.15.2, so this regression only happened with the 4.0.0 update.

**Comment by zeenix** [comment]
> It is linked above here: https://github.com/GNOME/gnome-shell/blob/main/js/ui/status/powerProfiles.js#L107

Thanks but that's part of the shell. It would be nice to get some command/script that I can run locally. I run GNOME so gjs is available.

**Comment by zeenix** [comment]
> It works fine with zbus 3.15.2, so this regression only happened with the 4.0.0 update.

Ah, 3.x to 4.x is a much bigger change so something might have changed in a way that gio (which I think is what gnome-shell is using) but as I wrote, this can easily be a bug in gnome-shell, gio or gio's gjs bindings but just only reproducible with zbus 4.

**Comment by mmstick** [comment]
I do not have any local scripts because I'm working specifically on integrating system76-power with GNOME 46 for Ubuntu and Fedora. It needs to work without requiring any modifications or extensions to gnome-shell. I can eventually attempt to bisect the issue, but zbus 3.15.2 does the job at the moment, so I'll revisit when I have time.

**Comment by zeenix** [comment]
Let me know when you've more info and I'll reopen then.

**Comment by zeenix** [comment]
Seems [someone else is now also seeing an issue with properties](https://github.com/hrkfdn/ncspot/issues/1449) which could have the same underlying source. I'm investigating more tomorrow.

**Comment by craigcabrey** [comment]
I can reproduce this reliably. Let me know if you need/want a full standalone repro.

**Comment by zeenix** [comment]
@craigcabrey awesome. Yes please. Try to make it as minimal as possible. 🙏

**Comment by craigcabrey** [comment]
This does the trick for me: https://gist.github.com/craigcabrey/1330a8ad10796f98f5a56cb5fcf6f619

**Comment by zeenix** [comment]
> This does the trick for me: https://gist.github.com/craigcabrey/1330a8ad10796f98f5a56cb5fcf6f619

Thanks for that. Monitoring the traffic with `busctl` reveals the problem:

```
‣ Type=method_call  Endian=l  Flags=0  Version=1 Cookie=13  Timestamp="Wed 2024-05-08 10:28:09.974283 UTC"
  Sender=:1.1894  Destination=:1.1885  Path=/net/hadess/PowerProfiles  Interface=org.freedesktop.DBus.Properties  Member=Set
  UniqueName=:1.1894
  MESSAGE "ssv" {
          STRING "net.hadess.PowerProfiles";
          STRING "ActiveProfile";
          VARIANT "s" {
                  STRING "client-provided-value";
          };
  };

‣ Type=signal  Endian=l  Flags=0  Version=1 Cookie=8  Timestamp="Wed 2024-05-08 10:28:09.974595 UTC"
  Sender=:1.1885  Path=/net/hadess/PowerProfiles  Interface=org.freedesktop.DBus.Properties  Member=PropertiesChanged
  UniqueName=:1.1885
  MESSAGE "sa{sv}as" {
          STRING "net.hadess.PowerProfiles";
          ARRAY "{sv}" {
                  DICT_ENTRY "sv" {
                          STRING "ActiveProfile";
                          VARIANT "s" {
                                  STRING "client-provided-value";
                          };
                  };
          };
          ARRAY "s" {
                  STRING "ActiveProfile";
          };
  };

‣ Type=method_return  Endian=l  Flags=0  Version=1 Cookie=9  ReplyCookie=13  Timestamp="Wed 2024-05-08 10:28:09.974667 UTC"
  Sender=:1.1885  Destination=:1.1894
  UniqueName=:1.1885
  MESSAGE "" {
  };
```

We are invalidating the property for some reason.
