### ISSUE TITLE
zvariant: Refactor deserializers to use boxed variant struct fields

### ISSUE THREAD

**Issue by jonathanhood** [dbus2/zbus#772]
I’m seeing an issue with how `zvariant::Value` is handled during deserialization. A `Value` is essentially the rust representation of a DBus variant. This is a value which has a type signature on the wire and some following data that is encoded per the type signature preceding. This requires some extra smarts in the serializer and deserializer to handle properly.

During serialization this is handled by boxing the values in a structure with fields `zvariant::Value::Signature` and `zvariant::Value::Value`. When encoding to DBus format these field names serve as hints to the serializer about what’s going on (please encode a variant’s signature and value). When encoding in other formats (e.g. JSON) this allows the variant information to be retained by simply boxing its two components together in a way that is straightforward.

During deserialization a similar approach is not applied. Calling `Value::deserialize` instead calls `deserialize_any` which tries to its best to map the type in the type signature to some call on the deserializer. This allows any concrete value to be turned in a `Value` whether or not is has a wire encoded type signature. `deserialize_any` _does_ make an attempt to handle real variant types correctly by calling `deserialize_seq` and taking the first element as the signature and the second element as the value - but it gets confused rather easily - especially in the case where the contained variant type _is an array_. It also doesn’t handle the boxing given by the serializer at all. 

There _is_ a sidecar deserialize called `DeserializeValue` which tries to deal with that boxing, but it is specifically geared towards situations where the concrete type of the variant is known/expected by the client code. As a result, it’s not a replacement for proper handling of variant types during deserialization.

By changing the deserialization of `Value` to adhere to the boxing we can use the same hinting strategy that the serializer uses for the deserializer to simplify that logic. We’ll also be able to handle encodings to non-DBus formats in more transparent way via the boxed representation. I think that’s a better overall approach - and the same approach be used to better handle things like `ObjectPath` as well.

So, I’d like to propose that the `Value` deserializer changes to use and expect this boxing strategy. I’d also propose that it should _only_ handle deserialization for true variant types and not call `deserialize_any` to try and map concrete types. This, unfortunately, is a breaking behavior change but is “more correct” and should lead to simpler code for handling these use cases. I suspect that’s a large enough change that it would be considered API breaking. If necessary, some kind of compatibility could be be built where non-variant encodings are handled but describing the behavior might be hard and would ideally the compatibility code would be pulled in a future major rev for simplicity.

Looking for feedback before proceeding down this path. Thanks for reading all this and considering!

**Comment by jonathanhood** [comment]
This is somewhat related to #549 - at least I think this approach is an enabler for achieving that goal

**Comment by jonathanhood** [comment]
> > `deserialize_any` _does_ make an attempt to handle real variant types correctly by calling `deserialize_seq` and taking the first element as the signature and the second element as the value - but it gets confused rather easily - especially in the case where the contained variant type _is an array_.
> 
> How so? Could you please provide a test case for this?

It's a bit hard to show a reproduction using what's in `main` today because of issues various other issues currently there with handling of variants. This discussion is a bit looking ahead to where some of those issues are resolved and a client can get to this point.

That said, here's the reproduction. If you trace this in a debugger you end up in `zvariant::dbus::de::ValueDeserializer` who is _quite_ thoroughly upset with this situation. Serde ends up calling `deserialize_u8`  while trying deserialize a `Vec<u8>` directly but it really needs to decode the signature and then the inner value. As a result, it decodes an array that looks _completely_ wrong (containing bytes of what is really the signature.

## Cargo.toml

```rust
[package]
name = "repro"
version = "0.1.0"
edition = "2021"

[dependencies]
zvariant = { git = "https://github.com/jonathanhood/zbus.git", branch = "fix/serialize-variant-types" }
serde = "1.0"

```

## Reproduction
```rust
use serde::{Deserialize, Serialize};
use zvariant::{serialized::{Context, Data}, Type, Value};

#[derive(Debug, Serialize, Deserialize, Type)]
#[zvariant(signature = "(v)")]
struct ArrayData {
    data: Vec<u8>
}

fn main() {
    let context = Context::new_dbus(zvariant::Endian::Little, 0);

    let serialized: Vec<u8> = vec![
        0x04, '(' as u8, 'a' as u8, 'y' as u8, ')' as u8, 0x00, // Signature
        0x00, 0x00, // Pad to 8-byte boundary for struct

        0x03, 0x00, 0x00, 0x00, // Array Length
        0x01, 0x02, 0x03 // Array Data
    ];

    {
        let data = Data::new(serialized.clone(), context);
        let (value, _): (Value<'_>, usize) = data.deserialize_for_signature("v").unwrap();
        
        if let Value::Structure(structure) = value {
            if let Some(Value::Array(array)) = structure.fields().get(0) {
                assert_eq!(array.len(), 3);
                assert_eq!(array[0], Value::U8(1));
                assert_eq!(array[1], Value::U8(2));
                assert_eq!(array[2], Value::U8(3));
            } else {
                panic!("Expected Value::Array");
            }
        } else {
            panic!("Expected Value::Structure");
        }
    }

    {
        let data = Data::new(serialized, context);
        let (array_data, _): (ArrayData, usize) = data.deserialize_for_signature("v").unwrap();

        assert_eq!(array_data.data.len(), 3, "Expected length 3 array of correct array data - got: {:?}", array_data.data);
        assert_eq!(array_data.data[0], 1);
        assert_eq!(array_data.data[1], 2);
        assert_eq!(array_data.data[2], 3);
    }
}
```

## Expected Output

Binary runs to completion with no issues:

## Actual Output

```
thread 'main' panicked at src/main.rs:41:87:
called `Result::unwrap()` on an `Err` value: Message("Could not parse signature from variant type")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jonathanhood** [comment]
> > It also doesn’t handle the boxing given by the serializer at all.
> 
> Don't get this either. What part of the boxing it's not making use of?

This can be demonstrated with what's in `main` by trying to hop the encoding through JSON. If you look at this error on. debugger you can see that the deserialization step calls `deserialize_any` which, in turn, calls `deserialize_seq` and things get messed. Because of this variation in behavior between the serialization and deserialization steps the handling of variants isn't a reflexive operation in terms of how serde sees it.

## Reproduction

```rust
use serde::{Deserialize, Serialize};
use zvariant::{OwnedValue, Type, Value};

#[derive(Debug, Serialize, Deserialize, Type)]
#[zvariant(signature = "(v)")]
struct ArrayData {
    data: Vec<u8>
}

fn main() {
    let input: Value<'_> = Value::Str("Hello World".into());

    let encoded = serde_json::to_value(&input).unwrap();
    println!("Encoded: {:?}", encoded);

    assert_eq!(encoded, serde_json::json!({
        "zvariant::Value::Signature": "s",
        "zvariant::Value::Value": "Hello World"
    }));

    let output: OwnedValue = serde_json::from_value(encoded.clone()).unwrap();
    assert_eq!(output, input.try_to_owned().unwrap());
}

```

## Expected Output

The `Value` can be decoded from it's boxed representation - so the program ends without error.

## Actual Output

```
Encoded: Object {"zvariant::Value::Signature": String("s"), "zvariant::Value::Value": String("Hello World")}
thread 'main' panicked at src/main.rs:21:70:
called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"zvariant::Value::Signature\", expected a borrowed string", line: 0, column: 0)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jonathanhood** [comment]
After spiking on this code for a bit, I think the issue comes down to code have two different but somewhat related expectations for what `Value` is:

- Some pieces of code expect Value to be a handler for DBus variant types.
- Some pieces of code expect Value to be more of an AST that can represent any conceivable DBus message.

Now, any handler of variant types can conceivable _also_ be an AST due to the nature of variant types. The issue with mixing these concepts, though, can be boiled down into two questions:

- When we actually go to encode should I encode the variant type signature or not?
- When decoding - should I retain a variant type signature or not?

A quick truth table for those questions and how they are handled today:

|  Target | Variant Type Encoded? | Variant Type Decoded? |
| --- | --- | --- |
| `Value<'_>` | Yes | Yes |
| `T` | No | No |

On the surface this makes sense, but with what I'm trying to do with #746 necessitates more nuanced handling. In that case some value `T` (which rust knows the concrete type of) may need to be encoded as a variant so we manually set the signature to "v".

I've also seen places where `Value` was directly deserialized from some primitive type on the weird (e.g. a `u`) without the variant type signature. This expectation seems to be encoded in various tests. That indicates an expectation that `Value` is more of an AST than a variant wrapper.

So, the table expands:

|  Target | Variant Type Encoded? | Variant Type Decoded? |
| --- | --- | --- |
| `Value<'_>` | Yes | Yes |
| `Value<'_>` from non `v` | ??? | ??? |
| `T` | No | No |
| `T` as `v` | ??? | ??? |

The code, predictably, handles the parts with "???" in sometimes surprising/inconsistent ways. Since this is essentially a core request to handle from #744 I'm naturally butting up against it.

**Comment by zeenix** [comment]
> > > `deserialize_any` _does_ make an attempt to handle real variant types correctly by calling `deserialize_seq` and taking the first element as the signature and the second element as the value - but it gets confused rather easily - especially in the case where the contained variant type _is an array_.
> > 
> > 
> > How so? Could you please provide a test case for this?
> 
> In the following example I deserialize a variant (that's really a `ay` under the hood).

The example you gave is currently of an unsupported case of decoding a Value as a concrete type. It's not that `deserialize_seq` get confused.

While I appreciate you explaining everything in detail, I really think in the end we just have 1-2 issues and the rest is just details of fixing those. I will close this now.
