### ISSUE TITLE
Invalid documentation links for object manager doc

### ISSUE THREAD

**Issue by fmartinsons** [dbus2/zbus#790]
Hello,

I fall upon dead links in [doc.rs page](https://docs.rs/zbus/latest/zbus/fdo/struct.ObjectManagerProxy.html).
All the links zbus::Proxy doc point to nowhere , from what I can see, it just misses a "proxy" level in the url (e.g. https://docs.rs/zbus/latest/zbus/struct.Proxy.html#method.receive_signal instead of https://docs.rs/zbus/latest/zbus/proxy/struct.Proxy.html#method.receive_signal)

I would have provide fix but I don't know how to test such a doc fix (moreover, the link are generated inside a macro)

**Comment by zeenix** [comment]
Thanks so much for pointing this out.

> I would have provide fix but I don't know how to test such a doc fix

You can either generate the docs locally and check manually (using `cargo doc --open`) or leave the testing to me.

**Comment by fmartinsons** [comment]
Ok, if it's that simple, I'll give it a try and suggest a merge request
