### ISSUE TITLE
Regression - interface functions cannot run concurrently

### ISSUE THREAD

**Issue by dvhar** [dbus2/zbus#799]
4.2.1 has a bug that causes interface functions be unable to run concurrently. It happens whether the functions are on the same interface or not. It is a regression because it worked fine in 4.1.2. I don't know exactly which version it started on, but I heard on matrix that there was a refactor recently that could have done it.
I put repro instructions in the zbus_regression branch of the repo where I found it:
[https://github.com/dvhar/pikeru/tree/zbus_regression](https://github.com/dvhar/pikeru/tree/zbus_regression)

**Comment by zeenix** [comment]
@elmarco As I suspected this is a regression from your PR:

```
91abff76a964d9c2ba7907435886ee9810395d02 is the first bad commit
Author: Marc-André Lureau <marcandre.lureau@redhat.com>

    ✨ zm: add `spawn` attribute on interface
```

**Comment by dvhar** [comment]
Thanks for fixing and for the great library
