### ISSUE TITLE
RFC: Drop vsock support

### ISSUE THREAD

**Issue by zeenix** [dbus2/zbus#830]
We added vsock support back a few years ago in anticipation of it being accepted in the [D-Bus spec and reference implementation](https://gitlab.freedesktop.org/dbus/dbus/-/merge_requests/200). However, this never happened and it's very unlikely to happen as the discussion has died out.

Moreover, I do not know if anyone is actually using it at all. Given that it's a maintenance burden and we've more work than developer/maintenance time available, I'm leaning towards removing this. The fact that we don't have any tests for this, means that we don't even know if this support actually works and when/if it breaks. We also sometimes have [issues with it](https://github.com/dbus2/zbus/pull/809#issuecomment-2129699731).

If you disagree, this is your chance to speak up.

**Comment by zeenix** [comment]
@elmarco ^

**Comment by elmarco** [comment]
I still wish some day a guest bus can be accessed from a host easily, or some guest services be on a VM host bus. Unfortunately, working on VM & desktop is not very popular.. Even ssh over vsock is very recent, thanks to Lennart systemd-ssh-proxy..

**Comment by zeenix** [comment]
> I still wish some day a guest bus can be accessed from a host easily, or some guest services be on a VM host bus.

I wish that too.

> How bad is maintainance of the vsock feature?

Not a lot but given we've no testing for this in the CI, I don't even know if it actually works and wouldn't know if I (or anyone) breaks it.

**Comment by zeenix** [comment]
@elmarco btw you didn't answer to most important question: are you relying on the vsock support of zbus?

**Comment by elmarco** [comment]
> @elmarco btw you didn't answer to most important question: are you relying on the vsock support of zbus?

not atm

**Comment by elmarco** [comment]
But there are some tests for vsock in CI already.

**Comment by zeenix** [comment]
> But there are some tests for vsock in CI already.

Compile-only. It doesn't tell us the impl really works.

**Comment by zeenix** [comment]
Thanks to @elmarco we now have tests for vsock that run in the CI (I hope?). So we can close this.
