### ISSUE TITLE
Generate `fdo` proxies through the respective `interface`

### ISSUE THREAD

**Issue by zeenix** [dbus2/zbus#842]
Now that it's possible, we should do this for sure. I [even implemented it](https://github.com/zeenix/zbus/commits/wip/fdo-automate-proxy-gen/) but unfortunately (at least at the moment), this will require API break. Definitely something for 5.0.

If anyone else takes this, do look at my WIP branch linked above.

**Comment by TheButlah** [comment]
This would be such an awesome feature 🙏

**Comment by zeenix** [comment]
@TheButlah yeah but keep in mind that it'll only be good for zbus maintenance. The `interface` macro already supports generation of `proxy`. This issue is just about using it ourselves for `fdo` module, where we currently use `interface` and `proxy` separately.

**Comment by TheButlah** [comment]
ah, my knowledge is out of date. I see it [here](https://dbus2.github.io/zbus/service.html#proxy-generation). Thanks!
