### ISSUE TITLE
Replace enumflags2 with bitflags

### ISSUE THREAD

**Issue by bilelmoussaoui** [dbus2/zbus#850]
Reasons:
- bitflags is already pulled in zbus through rustix/nix
- bitflags is way too popular, so the possibility an app/service that uses zbus depending on bitflags already is higher than enumflags. especially that bitflags is used by a lot of low level crates like nix/rustix/redox-syscall and so on. (2578 reverse dependencies vs 101, a bunch of the 101 are zbus based :p)

Not great:
- bitflags is approximately 2.6 the size of enumflags.

**Comment by zeenix** [comment]
@bilelmoussaoui so what's the verdict on this one? Given the tiny size of enumflags2 and its better ux (IMO) I'm leaning towards not doing this.

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui so what's the verdict on this one? Given the tiny size of enumflags2 and its better ux (IMO) I'm leaning towards not doing this.

I haven't had the time to look into the possibility of just adding a new feature that would enable bitflags integration so one could choose between bitflags or enumflags2.

**Comment by zeenix** [comment]
> I haven't had the time to look into the possibility of just adding a new feature that would enable bitflags integration so one could choose between bitflags or enumflags2.

Please no. If there is a compelling reason to switch to bitflags, we should just do that only.

**Comment by zeenix** [comment]
Ok, I'm closing it for now then before I forget about it.
