### ISSUE TITLE
Does zbus works with systemd socket activation on remote host?

### ISSUE THREAD

**Issue by johnnypea** [dbus2/zbus#852]
Can somebody please provide working example starting the zbus server instance on socket activation?

zbus server running as systemd service on Host1

zbus client running on Host2 connecting to TCP socket on Host1

Is this possible using peer to peer connection? Thank you.

**Comment by zeenix** [comment]
This is completely out of scope of zbus. If you use the D-Bus broker, your distro package setup everything for you. If you use peer-to-peer, you need to install the systemd socket file in the appropriate location. 

In any case, it's not something zbus can possibly help with.
