### ISSUE TITLE
Allow using zbus::proxy without async runtime (async-less build)

### ISSUE THREAD

**Issue by z33ky** [dbus2/zbus#928]
I've enhanced a `zbus-xmlgen`'d interface and wish to publish this.
That crate shouldn't dictate an async runtime, meaning ideally I could
```toml
[dependencies]
zbus = { version = "4.4.0", default-features = false }
```
But that breaks running e.g. `cargo doc` on that crate by itself, because selecting either `async-io` or `tokio` is required.

My crate only really needs some type definitions, specifically `zbus::Result` and `zbus::Error`, as well as the `zbus::proxy` macro (and whatever types that needs).

This could be solved by either enabling a feature-less `zbus` crate to build, removing or stubbing `zbus::connection` and whatever else won't make sense, or by splitting off a new, async-less `zbus_types` crates, containing the aforementioned types sufficient for defining the proxy types, which hopefully don't depend on an async runtime.

**Comment by zeenix** [comment]
`async-io` works fine with combined other runtimes, except tokio (which is one of the reasons we provide the special tokio integration feature): https://github.com/dbus2/zbus/blob/main/zbus/README.md#compatibility-with-async-runtimes

**Comment by zeenix** [comment]
> That crate shouldn't dictate an async runtime, meaning ideally I could

That's easily said, than done. 😂 Most crates just force tokio on you and you can't really use them with other runtimes easily then. We work by default with all runtimes (through async-io, which is not a complete runtime, btw).

This is an I/O API and hence primarily async. We also provide [a blocking API](https://github.com/dbus2/zbus/blob/main/zbus/README.md#blocking-api) that completely abstracts async from you, which is useful for simple cases.

However, if you have concrete ideas on how we can do better, please do share.

**Comment by z33ky** [comment]
I think I'll just provide a default "async-io" and non-default "tokio" feature like zbus then.
Thanks for responding anyways :+1:

**Comment by zeenix** [comment]
That's not a bad idea IMO.


Believe me, I'm not 100% satisfied with our solution either but this is a general issue in the Rust ecosystem. I did a presentation about this struggle a while back. You can watch the recording [here](https://youtu.be/w1vKAUor-4o), if you're interested.
